nhn/tui.grid

src/js/grid.js
src/js/model/summary.js
test/unit/js/model/summary.spec.js

Add `getSummaryValues()` method
(works only when the summary option exists)
```js
const summaryC1 = grid.getSummaryValues('c1');
console.log(summaryC1);
/*
{
sum: 1000,
avg: 200,
max: 300,
min: 50,
cnt: 5
}
*/
```
```js
const summaryAll = grid.getSummaryValues();
console.log(summaryAll);
/*
{
c1: {
sum: 1000,
avg: 200,
max: 300,
min: 50,
cnt: 5
},
c2: {
sum: 2000,
avg: 300,
max: 600,
min: 80,
cnt: 5
}
}
*/
```
---

feat: add getSummaryValues API (close #195, #240)

---

index.d.ts

fix: wrong type definition (ref #321)
The rowHeaders of IGridOptions of index.d.ts is defined differently from the document.
ref) #321 
---

fix: type definition. rowHeaders of IGridOptions of index.d.ts #321

---

cypress/integration/data.spec.ts
cypress/integration/index.spec.ts
cypress/plugins/index.js
src/dispatch/data.ts
src/grid.tsx
src/helper/common.ts
src/helper/reactive.ts
src/store/data.ts
src/types.d.ts
src/view/bodyRows.tsx
src/view/hoc.tsx

- `resetData()`
- `removeRow()` / `clear()` 
- `getRow()` / `getRowAt()` /  `getRows()` / `getIndexOfRow()` / `getRowCount()`
- Make sure that original object is not mutated. (returns new object)
- Internal properties - `__storage__` , `__handlerMap__` - became not enumerable
- Added `getOriginObject` function
- Throws error when given object is already reactive or array type
---

feat:  remove / setter / getter APIs

---

cypress/integration/data.spec.ts
src/dispatch/data.ts
src/store/focus.ts
src/view/bodyCell.tsx

#473
**fixed**
*  if the removed row includes focus, editing layer, initialize them.
* get row span by row key in calculating focus cell position'
* selectedRow is judged by row index not row key in the bodyCell component.
**etc**
* add cypress test case
---

fix: init focus when remove row

---

src/js/model/data/treeRowList.js
test/unit/js/model/data/treeRowList.spec.js

* Calling `expandAll` or `collapseAll` APIs prevented the `expanded` or `collapsed` events from being executed.
* To prevent `expanded` or `collapsed` events when calling the `expandAll` or `collapseAll` APIs, the user must explicitly block them using the `off` method.
```js
grid.on('expanded', () => {
// ...
});
grid.on('expandedAll', () => {
grid.off('expanded');
});
```
---

fix: change logic to invoke expanded and collapsed events (close #396)

---

cypress/helper/customLayerEditor.ts
cypress/integration/editor.spec.ts
index.d.ts
src/grid.tsx
src/query/data.ts
src/view/editingLayerInner.tsx

* The editing layer would be destroyed automatically only for changing the focused cell or pressing the enter key.
* Add `finishEditing()` API, so that users can decide the destroying point using this API.
---

fix: modify the point for destroying cell editor 

---

src/css/grid.css
src/dispatch/viewport.ts

* sync the scroll with focus, selection.
* remove left-side z-index css property to prevent hiding the bottom of the focus layer.
---

fix: sync scroll for moving in selection, focus

---

cypress/integration/dataSource.spec.ts
cypress/integration/modifiedDataManager.spec.ts
src/dataSource/modifiedDataManager.ts

* fixed that the duplicated data is added to createdRows and updatedRows on modifying the created data(#502).
---

fix: getModifiedRows method

---

cypress/integration/tree.spec.ts
examples/data/tree-dummy.js
examples/example14-tree.html
samples/tree.ts
src/dataSource/serverSideDataProvider.ts
src/dispatch/tree.ts
src/grid.tsx
src/helper/tree.ts
src/store/rowCoords.ts
src/store/types.ts

1. Add dynamic loading data.
```js
const treeData = [
{
name: 'c1',
_children: [] // Set to empty array then row has toggle button 
}
]
```
2. Fix that fire `expand` or `collapse` event.
* `expand` or `collapse` event is not fired when calling `expandAll` or `collapseAll`.
* `expand` or `collapse` event is not fired every expanded or collpased row.
```js
grid.on('expand', (ev) => {
// ...
});
grid.expand();
grid.expandAll();
```
3. Bind `dataSoucre` on tree data
```js
const instance = new Grid({
// ...
treeColumnOptions: {
name: 'c1'
},
data: {
api: {
readData: { url: '/api/readData', method: 'GET' }
}
}
});
grid.on('expand', (ev) => {
const { rowKey: parentRowKey } = ev;
const childRowKeys = grid.getChildRows(rowKey);
if (!childRowKeys.length) {
grid.readData(1, { parentRowKey });
// …
```

feat: bind tree data source

---

src/dispatch/summary.ts

* fixed calculating summary's logic when reset columns
---

fix: calculate summary when reset columns

---

src/view/editingLayerInner.tsx

fix: Remove 'el' variable reference from EditingLayerInnerComp class (#652)
Remove 'el' variable reference from EditingLayerInnerComp class
Change to using 'editorEl' variable
---

fix: Remove 'el' variable reference from EditingLayerInnerComp class (#652)

---

cypress/integration/rowHeaders.spec.ts
src/dispatch/data.ts
src/store/data.ts

`checkedAllRows` previously managed as an observable
There was only a getter that checked and returned a check in row.
However, the Observer does not work properly when in dynamic rendering.
Therefore, changed the `checkedAllRows` variable to be managed manually.
Inside the checkAll, uncheckAll, check, uncheck methods
Added code to manually change the value of `checkedAllRows`.
---

fix: Manually change 'checkedAllRows' in observable (#662)

---

cypress/helper/runMockServer.ts
cypress/integration/dataSource.spec.ts
docs/ko/pagination.md
src/dataSource/serverSideDataProvider.ts
src/dispatch/data.ts
src/grid.tsx
src/view/pagination.tsx

* changed the paging count properly when calls setPerPage API.
* setPerPage API is operated in client pagination.
* related issue(#667)
---

fix: changed the paging count properly when calls setPerPage API (#667)

---

cypress/integration/editor.spec.ts
cypress/integration/eventBus.spec.ts
cypress/integration/filter.spec.ts
cypress/integration/lazyObservable.spec.ts
cypress/integration/relation.spec.ts
src/dispatch/data.ts
src/dispatch/filter.ts
src/dispatch/focus.ts
src/editor/text.ts
src/grid.tsx
src/helper/render.ts
src/query/focus.ts
src/store/focus.ts
src/store/types.ts
src/view/editingLayerInner.tsx

* made synchronous rendering on start or finish editing.
*  DOM update of the editing cell has to be synchronous on calling startEditing, finishEditing API . Because the previous editing cell should be destroyed in case of calling finishEditing, startEditing API in a row.
* finishEditing API has been changed for `undefined` value parameter.
* as the value parameter is `undefined`, the editor's value is saved the and finish editing.
* related issue(#682, #686)
---

fix: makes synchronous rendering on start or finish editing(#682, #686)

---

src/view/bodyDummyRow.tsx

Incorrectly calculating `isOddRow` variable in `bodyDummyRow.tsx`
**This is the result in storybook. (stories/dummyRows.stories.ts)**
**Before**
**After**
---

fix: isOddRow bug fix in bodyDummyRow

---

packages/toast-ui.grid/src/view/datePickerFilter.tsx

Changed filter date format.
But, datepicker close and reopen the format is initialized.
---

fix: bug that initialize filter date format

---

packages/toast-ui.grid/cypress.json
packages/toast-ui.grid/cypress/integration/datePicker.spec.ts
packages/toast-ui.grid/cypress/plugins/index.js
packages/toast-ui.grid/index.html
packages/toast-ui.grid/src/css/grid.css
packages/toast-ui.grid/src/editor/datePicker.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/view/datePickerFilter.tsx
packages/toast-ui.grid/types/tui-date-picker/index.d.ts
packages/toast-ui.grid/webpack.config.js

* focused the editing cell properly when datepicker layer is closed
---

fix: focus the editing cell when datepicker layer is closed

---

packages/toast-ui.grid/cypress/integration/columnOptions.spec.ts
packages/toast-ui.grid/src/view/bodyCell.tsx

* calculated with cell border width when refresh row height
* need to add visual test in storybook
* bug page: https://nhn.github.io/tui.grid/latest/tutorial-example12-whitespace
---

fix: calculate with cell border width when refresh row height

---

packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/src/store/data.ts
packages/toast-ui.grid/src/store/types.ts

* changed setting rowKey on calling `setRow` API
* before
```js
const { rawRow, viewRow, prevRow } = getCreatedRowInfo(store, rowIndex, row);
rawRow.rowKey = orgRow.rowKey;
viewRow.rowKey = orgRow.rowKey;
```
* after
```js
const { rawRow, viewRow, prevRow } = getCreatedRowInfo(store, rowIndex, row, orgRow.rowKey);
```
* removed to call function to initialize focus layer
---

refactor: setting rowKey in setRow api

---

packages/toast-ui.grid/src/dispatch/data.ts

related issue: #838 
`check`, `uncheck` events are triggered before set the checked property.
so, have reordered that process.
---

fix: reorder process order of  and event(#838)

---

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts
packages/toast-ui.grid/cypress/integration/focus.spec.ts
packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts
packages/toast-ui.grid/cypress/integration/theme.spec.ts
packages/toast-ui.grid/cypress/support/commands.js
packages/toast-ui.grid/cypress/support/index.d.ts
packages/toast-ui.grid/src/grid.tsx

fix: move the scroll position on calling `focus`, `focusAt`API(#873)

---

packages/toast-ui.grid/cypress/integration/attributes.spec.ts
packages/toast-ui.grid/cypress/integration/column.spec.ts
packages/toast-ui.grid/cypress/integration/dataSource.spec.ts
packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts
packages/toast-ui.grid/index.d.ts
packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts
packages/toast-ui.grid/src/dispatch/column.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/helper/common.ts
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/src/renderer/rowHeaderInput.ts
packages/toast-ui.grid/src/renderer/types.d.ts
packages/toast-ui.grid/src/store/column.ts
packages/toast-ui.grid/src/store/create.ts
packages/toast-ui.grid/src/store/data.ts
packages/toast-ui.grid/src/store/helper/tree.ts
packages/toast-ui.grid/src/store/types.ts
packages/toast-ui.grid/src/types.d.ts
packages/toast-ui.grid/src/view/bodyCell.tsx
packages/toast-ui.grid/src/view/container.tsx
packages/toast-ui.grid/src/view/headerCheckbox.tsx

* related issue(#887)
* create `_disabledPriority` property of row to know the priority between `column disabled` and `row disabled` internally.
* It has been considered to save ‘disabled’ state on each cell, but this would affect initial rendering performance and makes the duplicated state which is same as `valueMap` of `viewRow`.
---

feat: `enableColumn`, `disableColumn` api(#887)

---

packages/toast-ui.grid/cypress/integration/validation.spec.ts
packages/toast-ui.grid/index.d.ts
packages/toast-ui.grid/src/store/data.ts
packages/toast-ui.grid/src/store/types.ts

* related issue(#910)
* the `row`(not `rowKey`) should be passed  as the parameter, because when `validatorFn` is executed the grid instance is not created yet.
```js
const grid = new tui.Grid({
el,
data,
columns: [
{
header: 'Price',
name: 'price',
validation: {
validatorFn: (value, row, columnName) => {
// cannot use as below, because the grid instance is not created on calling `validatorFn`
// grid.getValue(row.rowKey, columnName);
return value !== 11000
}
}
},
// ...
]
});
```
---

feat: add validatorFn parameters(#910)

---

packages/toast-ui.grid/cypress/integration/column.spec.ts
packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/cypress/integration/focus.spec.ts
packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/focus.ts
packages/toast-ui.grid/src/dispatch/sort.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/query/validation.ts

* checked cell state(`disabled`, `editable`) in `setColumnValues` API
```js
targetRow[columnName] !== value && (!checkCellState || (!disabled && editable))
```
---

fix: check disabled, editable state in setColumnValuesAPI

---

packages/toast-ui.grid/src/dispatch/renderState.ts

Error when calling `refreshRowHeight` when `rowHeight` is `auto`
[`cellHeightMap`](https://github.com/nhn/tui.grid/blob/41b70cc9433f18d7bf7bd3da4d52238c64d57c12/packages/toast-ui.grid/src/dispatch/renderState.ts#L45) manages only the values ​​of visible rows.
but, [`refreshRowHeight`](https://github.com/nhn/tui.grid/blob/41b70cc9433f18d7bf7bd3da4d52238c64d57c12/packages/toast-ui.grid/src/dispatch/renderState.ts#L43) method is called for the entire row.
therefore, an error occurs because the [`cellHeights`](https://github.com/nhn/tui.grid/blob/41b70cc9433f18d7bf7bd3da4d52238c64d57c12/packages/toast-ui.grid/src/dispatch/renderState.ts#L46) value undefined.
---

fix: Error when calling "refreshRowHeight"

---

packages/toast-ui.grid/cypress/integration/validation.spec.ts
packages/toast-ui.grid/src/helper/observable.ts
packages/toast-ui.grid/src/store/data.ts

* paused observation when calling validatorFn internally for preventing to register unnecessary observer
---

fix: pause observation when calling validatorFn internally

---

packages/toast-ui.grid/cypress/integration/dataSource.spec.ts
packages/toast-ui.grid/cypress/integration/validation.spec.ts
packages/toast-ui.grid/cypress/support/commands.js
packages/toast-ui.grid/cypress/support/index.d.ts
packages/toast-ui.grid/cypress/support/index.js
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/focus.ts
packages/toast-ui.grid/src/helper/common.ts
packages/toast-ui.grid/src/query/data.ts

* The timing of calling `validatorFn` is made lazy when calling `appendRow`, `setRow` to apply changed data
---

fix: make the timing of calling validatorFn lazy

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts

* The hidden column should be included in target column on calling `setValue` API for executing `onBeforeChange`, `onAfterChange` custom event callback
---

fix: the hidden column should be included in target column on setValue API

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/types/index.d.ts

* added `getFormattedValue` API to get formatted value. 
* `getFormattedValue(rowKey: RowKey, columnName: string): string`
* The API is useful to below example
```js
// ...
{
header: 'Grade',
name: 'grade',
formatter: 'listItemText',
}
// ...
// get formatted value
grid.getFormattedValue(0, 'grade')
```
---

feat: getFormattedValue API

---

packages/toast-ui.grid/examples/example03-custom-editor.html
packages/toast-ui.grid/src/css/grid.css
packages/toast-ui.grid/src/editor/checkbox.ts
packages/toast-ui.grid/src/editor/datePicker.ts
packages/toast-ui.grid/src/editor/dom.ts
packages/toast-ui.grid/src/editor/select.ts
packages/toast-ui.grid/src/editor/text.ts
packages/toast-ui.grid/src/view/clipboard.tsx
packages/toast-ui.grid/src/view/editingLayer.tsx
packages/toast-ui.grid/stories/editor.stories.ts

* related issue(#979)
* `position: fixed` is based on viewport as container block but when the one of the ancestors has `transform`, `perspective` and `filter`, container block is changed as that ancestor block. So, the position of the layer should be calculated by using fixed grid container block with `absolute` position.
---

fix: wrong editing layer position with translate style(#979)

---

packages/toast-ui.grid/cypress/integration/summary.spec.ts
packages/toast-ui.grid/src/dispatch/column.ts
packages/toast-ui.grid/src/dispatch/summary.ts
packages/toast-ui.grid/src/store/summary.ts

* fixed that summary content is not changed after calling `setColumns` API, because summary column cannot observe the added column data through `setColumns` API
* the reactivity of summary has been based on the column cells, but it changed to based on summary root structure for effectivity.
---

fix: change summary content after calling `setColumns` API

---

packages/toast-ui.grid/cypress/integration/filter.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/filter.ts
packages/toast-ui.grid/src/query/filter.ts
packages/toast-ui.grid/src/query/sort.ts
packages/toast-ui.grid/types/index.d.ts
packages/toast-ui.grid/types/options.d.ts

* should consider removing column filter state on calling `restetData` API option
---

fix: consider removing column filter state on calling `restetData` API option

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/types/dataSource/index.d.ts

* fixed that its' not possible to find the row properly on calling getRow API after calling clearModifiedData
---

fix: cannot find the row properly on calling getRow API after calling clearModifiedData

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts
packages/toast-ui.grid/src/dispatch/create.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/filter.ts
packages/toast-ui.grid/src/dispatch/lazyObservable.ts
packages/toast-ui.grid/src/dispatch/pagination.ts
packages/toast-ui.grid/src/dispatch/rowSpan.ts
packages/toast-ui.grid/src/dispatch/sort.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/src/query/validation.ts
packages/toast-ui.grid/src/store/create.ts
packages/toast-ui.grid/src/store/viewport.ts
packages/toast-ui.grid/types/store/data.d.ts

* related issue(#1053)
* classify the dispatch module for readablity
---

fix: script error is caused by calling `removeCheckedRows` API(#1053)

---

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts
packages/toast-ui.grid/src/view/bodyArea.tsx

* `scrollEnd` event is triggered after calling `resetData` API, because scroll left is initialized. To fix it, grid should compare previous scroll left with scroll left to be changed internally.
---

fix: scrollEnd event is triggered after calling resetData API

---

packages/toast-ui.grid/cypress/integration/tree.spec.ts
packages/toast-ui.grid/src/dispatch/tree.ts

* enhancement
* get the max text width using text length on the cells of resizable tree column for performance.
* bug fix
* js error is displayed when getting the computed font style.
* related PR(#953)
---

fix: the js error is emitted when expanding the tree cell with resizable option

---

packages/toast-ui.grid/src/store/data.ts
packages/toast-ui.grid/src/view/container.tsx
packages/toast-ui.grid/types/store/data.d.ts

- I couldn't find develop branch so I branched off master
- it's a feature
- I think it follows your guidelines
- I did not add Tests nor Documentation changes. I would like to understand if this feature is interesting enough to be accepted or not before investing that time
- It is not a breaking change
This change permits the developer to add a `position` property to the grid Pagination option to indicate if they want to have the pagination widget above or below the grid.
```
pageOptions: {
useClient: true,
perPage: 5,
position: 'bottom'
}
```
```
pageOptions: {
useClient: true,
perPage: 5,
position: 'top'
}
```
By default, if no position property is given the pagination will appear below as it does currently

feat: permit showing pagination on top of grid with pageOptions.position=top

---

packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/helper/observable.ts

*  If the row is removed, it will not be displayed properly.
* when the row is removed or moved, there is the problem that calling observer multiple times which makes changed data from being not applied.  we can resolve the issue through batched update which prevents the unnecessary calling observer.
---

fix: the removed row is not applied to grid properly

---

packages/toast-ui.grid/cypress/integration/validation.spec.ts
packages/toast-ui.grid/src/store/data.ts

* fixed that nullish or undefined cell value is changed to empty string in `validatorFn`
---

fix: nullish or undefined cell value is changed to empty string in `validatorFn`

---

packages/toast-ui.grid/cypress/integration/editor.spec.ts
packages/toast-ui.grid/src/dispatch/focus.ts
packages/toast-ui.grid/src/dispatch/keyboard.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/view/container.tsx

* fixed that copy prev editing value when `editingEvent` option is `click`
---

fix: copy prev editing value when `editingEvent` option is `click`

---

packages/toast-ui.grid/cypress/integration/observerble.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/helper/observable.ts
packages/toast-ui.grid/src/renderer/default.ts

* The performance of `check` API is drastically slow down with large data.
* example code
```js
for (let i = 0; i < 8000; i += 1) {
grid.check(i);
}
```
---

fix: improve `check`, `uncheck` API performance

---

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts
packages/toast-ui.grid/src/view/bodyArea.tsx

* `scrollEnd` event should not be triggered when scrollTop position equals `0`.
---

fix: trigger `scrollEnd` event when calling `clear` API

---

packages/toast-ui.react-grid/index.d.ts

This is a fix for issue #1260.
The list of available array items for `oneTimeBindingProps` has been copied from [the documentation](https://github.com/nhn/tui.grid/tree/ad36346efc8d19d17109a7e86ac9c297e055d098/packages/toast-ui.react-grid#reactive-props).
---

fix: add oneTimeBindingProps to React wrapper prop list (fix #1260)

---

packages/toast-ui.grid/src/query/clipboard.ts
packages/toast-ui.grid/src/view/clipboard.tsx

* as-is
* to-be
* as-is
* to-be
---

fix: copy the data without encoding

---

packages/toast-ui.grid/cypress/integration/dummyRows.spec.ts
packages/toast-ui.grid/src/view/bodyArea.tsx
packages/toast-ui.grid/src/view/bodyDummyRow.tsx
packages/toast-ui.grid/stories/dummyRows.stories.ts

fix: cannot show the dummy cells at the farthest right in scrollX

---

packages/toast-ui.grid/cypress/helper/util.ts
packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/cypress/integration/eventBus.spec.ts
packages/toast-ui.grid/cypress/integration/tree.spec.ts
packages/toast-ui.grid/docs/en/custom-event.md
packages/toast-ui.grid/docs/ko/custom-event.md
packages/toast-ui.grid/src/css/grid.css
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/helper/dom.ts
packages/toast-ui.grid/src/query/draggable.ts
packages/toast-ui.grid/src/query/tree.ts
packages/toast-ui.grid/src/store/column.ts
packages/toast-ui.grid/src/store/create.ts
packages/toast-ui.grid/src/store/helper/tree.ts
packages/toast-ui.grid/src/view/bodyArea.tsx
packages/toast-ui.grid/types/event/index.d.ts
packages/toast-ui.grid/types/index.d.ts
packages/toast-ui.grid/types/options.d.ts
packages/toast-ui.grid/types/store/column.d.ts
packages/toast-ui.grid/types/store/data.d.ts

we added move tree row functionality by dragging or `moveRow` API.
```js
const grid = new tui.Grid({
el: document.getElementById('grid'),
data: treeData,
draggable: true,
treeColumnOptions: {
name: 'name',
useCascadingCheckbox: true
},
// ...
}
```
* move to an another index
* append to another node
The user can customize the `draggable` row header column through existing `rowHeaders` option
```js
class DraggableRenderer {
constructor(props) {
const el = document.createElement('span');
el.innerHTML = `😀`;
el.style.cursor = 'pointer'
this.el = el;
}
getElement() {
return this.el;
}
render(props) {
this.el.innerHTML = `😀`;
}
}
const grid = new Grid({
el: document.getElementById('grid'),
data: treeData,
rowHeaders: [
{
type: 'draggable',
renderer: {
type: DraggableRenderer
}
},
], …
```

feat: tree drag and drop

---

packages/toast-ui.grid/src/helper/filter.ts
packages/toast-ui.grid/src/i18n/index.ts
packages/toast-ui.grid/src/view/datePickerFilter.tsx
packages/toast-ui.grid/src/view/filterLayerInner.tsx
packages/toast-ui.grid/src/view/selectFilter.tsx
packages/toast-ui.grid/src/view/textFilter.tsx
packages/toast-ui.grid/types/options.d.ts

* added i18n for filter select option
```js
const messages: OptI18nLanguage = {
en: {
// ...
filter: {
contains: 'Contains',
eq: 'Equals',
ne: 'Not equals',
start: 'Starts with',
end: 'Ends with',
after: 'After',
afterEq: 'After or Equal',
before: 'Before',
beforeEq: 'Before or Equal',
},
},
}
```
* related issue(#1234)
---

fix: add i18n for filter select option

---

packages/toast-ui.grid/cypress/integration/filter.spec.ts
packages/toast-ui.grid/src/dispatch/filter.ts
packages/toast-ui.grid/src/i18n/index.ts
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/src/view/selectFilter.tsx
packages/toast-ui.grid/types/options.d.ts

* remove empty values from select filter (fix #1245)
* Nil value handling when selectAll is selected
---

fix: Remove empty values from select filter (#1245)

---

packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/query/clipboard.ts

* fixed that emitting the script error when copying unobservable rows.
---

fix: emit script error when copying unobservable rows

---

packages/toast-ui.grid/cypress/integration/tree.spec.ts
packages/toast-ui.grid/src/dispatch/tree.ts

* fixed that cannot move tree node to last when last node has children
* related issue(#1358)
---

fix: cannot move tree node to last when last node has children

---

packages/toast-ui.grid/src/view/bodyArea.tsx

* fixed the grid body is hidden after resizing the grid
---

fix: the grid body is hidden after resizing the grid

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/src/grid.tsx

- Added an API that can get filtered data.
- It works similarly to the `getData` API, but it gets data from `filteredRawData` rather than `rawData`.
---

feat: add getFilteredData API (fix #1459)

---

packages/toast-ui.grid/src/view/filterLayerInner.tsx
packages/toast-ui.grid/src/view/heightResizeHandle.tsx

Fix for the cases when the grid is created of a `<form>` element. In those cases it's not possible to use filter buttons (nor the height resize handler). 
This pull request is similar to https://github.com/nhn/tui.grid/pull/1492
More details here: https://github.com/nhn/tui.grid/issues/1528
Thanks.
---

fix: add type=button in button elements (fix #1528) 

---

packages/toast-ui.grid/cypress/integration/editor.spec.ts
packages/toast-ui.grid/src/editor/checkbox.ts
packages/toast-ui.grid/src/editor/datePicker.ts
packages/toast-ui.grid/src/editor/dom.ts
packages/toast-ui.grid/src/editor/select.ts
packages/toast-ui.grid/src/helper/common.ts
packages/toast-ui.grid/src/view/editingLayer.tsx
packages/toast-ui.grid/types/editor/index.d.ts

* Fixed that where the position of the drop-down layer in the editor did not move when scrolling.
* The drop-down layer moves as you scroll.
* Hides the drop-down layer when the editing cell is moved out of the viewport by scrolling.
**As-Is**
**To-Be**
---

fix: editors with drop-down layer to follow scrolling

---

packages/toast-ui.grid/cypress/integration/attributes.spec.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/types/index.d.ts

* Added APIs to return added class names.
* In the case of a cell, the class name added to the column and row to which the cell corresponds is also returned.
* In the case of a column, only the class names added to the column in all rows are returned.
---

feat: add APIs that return added class names

---

packages/toast-ui.grid/cypress/integration/editor.spec.ts
packages/toast-ui.grid/src/view/editingLayer.tsx

- Related issue: #1576 
- Fixed an error that caused the editor to be destroyed before editing was completed.
- Simply, the problem is due to trying to get values from the editor after destroying it.
- So, fixed the editor to be destroyed later.
---

fix: dropdown layer removed before finishing editing (fix #1576)

---

packages/toast-ui.grid/cypress/integration/editor.spec.ts
packages/toast-ui.grid/src/editor/checkbox.ts
packages/toast-ui.grid/src/editor/datePicker.ts
packages/toast-ui.grid/src/editor/select.ts
packages/toast-ui.grid/src/view/editingLayer.tsx
packages/toast-ui.grid/types/editor/index.d.ts

* Fixed an issue that occurs when finishing editing by clicking on the other side.
* It was caused by trying to remove the element Even though the element was removed.
* Fixed to check if the element is mounted.
---

fix: occur error when finish editing by click the other side

---

packages/toast-ui.grid/cypress/integration/rowSpan.spec.ts
packages/toast-ui.grid/src/store/data.ts

* Fixed row spans breaking when scrolling.
* It is caused by observable data and row span attribute that will be depreacted.
* For performance, the grid set lazy observable to array values like data.
* Because of this, in initial, only data in viewport change to observable.
* When scrolling, the data incoming to viewport changes to observable.
* At this moment, rowSpanMap is set by rowSpan attribute(regardless It is already set).
* But, dynamic row span implements without row span attribute. It only uses real data.
* So, I fixed it to use rowSpanMap that was already set.
---

fix: dynamic row span with scroll

---

packages/toast-ui.grid/src/grid.tsx

* Extends the functionality of the [`resetColumnWidths`](https://nhn.github.io/tui.grid/latest/Grid#resetColumnWidths) method.
* Previously, an error occurred when did not pass a `widths` array to this method.
* So, I modified the behavior to reset auto column width when this array is not given.
---

feat: reset auto resizing column widths on resetColumnWidths

---

packages/toast-ui.grid/cypress/integration/datePicker.spec.ts
packages/toast-ui.grid/cypress/integration/editor.spec.ts
packages/toast-ui.grid/src/editor/checkbox.ts
packages/toast-ui.grid/src/editor/datePicker.ts
packages/toast-ui.grid/src/editor/select.ts
packages/toast-ui.grid/src/view/editingLayer.tsx
packages/toast-ui.grid/types/editor/index.d.ts

* Added the feature that is instant applying of built-in editor.
* It works only for built-in select, checkbox(radio), datePicker editor.
* For use this, pass the `instantApply` option to `true` in property of options of editor of column.
* If use it, apply new value by clicking a new value in the dropdown layer of built-in editor.
**Before use it**
**After use it**
---

feat: instant applying of built-in editor

---

packages/toast-ui.grid/docs/en/getting-started.md
packages/toast-ui.grid/docs/ko/getting-started.md

* Fixed incorrect CDN URL in getting started documentation.
---

docs: fix wrong CDN URL in getting started documents

---

packages/toast-ui.grid/cypress/integration/rowSpan.spec.ts
packages/toast-ui.grid/src/dispatch/rowSpan.ts

* Fixed an issue that the row spans released after editing some cell.
* It occurs by resetting row spans regardless of using dynamic row span.
* Changed to reset row spans when only using dynamic row span.
---

fix: maintain all row spans after editing some cell

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts

* Fixed that, Unlike the `appendRow` API, when new rows are added using the `appendRows` API, the rows are not added to the `createdRows` in the `modifiedData`.
* Fixed it by pushing each added row to the data manager with "CREATE". 
---

fix: add appended rows to modified data

---

packages/toast-ui.grid/src/dispatch/keyboard.ts
packages/toast-ui.grid/src/query/clipboard.ts

* Fixed an issue where data was truncated when pasting more rows than the number of rows in the grid.
* When calculating the range to be pasted during paste, if it exceeds the row range of the current grid, it adds as many blank rows as it exceeds and then performs pasting.
* The test could not be added due to a [Clipboard issue in Cypress](https://github.com/cypress-io/cypress/issues/2386).
**As-Is**
**To-Be**
---

fix: paste more rows than rows of the grid (fix #1635)

---

packages/toast-ui.grid/cypress/integration/rowHeaders.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts

related issue: #1667 
* Fixed the problem that rows in the view were not reflected when clicking the checkbox in the header area after sorting.
* This happened because in an observable data system, the data was transformed by sorting and not notified of changes normally.
**As-Is**
**To-Be**
---

fix: check buttons are not applied in view after sort (fix #1667)

---

packages/toast-ui.grid/cypress/integration/contextMenu.spec.ts
packages/toast-ui.grid/src/view/container.tsx
packages/toast-ui.grid/src/view/contextMenuItem.tsx

* Fixed the context menu to show inside the container.
* Instead of using the window's height and width, changed it to use the information from the container.
**As-Is**
**To-Be**
---

fix: context menu shows inside container

---

README.md
packages/toast-ui.grid/cypress/integration/renderer.spec.ts
packages/toast-ui.grid/package-lock.json
packages/toast-ui.grid/package.json
packages/toast-ui.grid/src/renderer/default.ts
packages/toast-ui.grid/src/view/clipboard.tsx

related issue: #1669 
* Fixed an issue that the XSS vulnerability by using DOMPurify.
---

fix: cross site script vulnerability (fix #1669)

---

packages/toast-ui.grid/cypress/integration/summary.spec.ts
packages/toast-ui.grid/src/dispatch/summary.ts

* Fixed an issue where the value of `filtered` in the `summary` value is not set properly when no filter is set.
* It was caused by not updating the value unless the filter was set.
* Fixed to return the same value as the default `summary` value if no filter is set.
* In addition, the problem that `min` and `max` was not updated correctly when the data of cells that had values corresponding to `min` and `max` was changed has been fixed.
---

fix: change filtered summary properly when no filter is set

---

packages/toast-ui.grid/src/dispatch/dimension.ts

* Fixed an issue where the height including the 'padding' of the parent element was set when the Grid's 'bodyHeight' was set to 'fitToParent'.
* This was caused by not subtracting the width of `padding` while setting the height using `clientHeight` which returns a value including `padding`.
**As-Is**
**To-Be**
---

fix: fit to parent height without padding (fix #1756)

---

packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/types/index.d.ts

* Added `setRows` API for setting multi rows
* Previously, the only way to set rows was the `setRow` API, which caused performance issues when setting multiple rows.
* As a result of self-test, when setting 8000 rows of 4 columns, it took about 100 seconds on average with the existing method, but about 600 ms on average when using the `setRows` API. (Performance improvement of about 150 times)
---

feat: add setRows api for setting multiple rows

---

packages/toast-ui.grid/src/query/validation.ts

* Fixed an issue that is occurring an error when calling [`validate`](https://nhn.github.io/tui.grid/latest/Grid#validate) with folded tree row.
* The tree row that has never been opened is not observable data. So, view data of it doesn't have any value properties.
* Because it doesn't have any properties needed for validating, The error occurred.
* So, before validating, check if there is non-observable row and then change it to an observable row.
---

fix: validate api occurs an error when there is folded tree row

---

packages/toast-ui.grid/src/view/bodyArea.tsx

* Fixed flickering new rows when scrolling.
* I don't know the exact reason, but it seems that the problem occurred as the browser did some performance optimizations, etc when automatically transitioning from the `wheel` event to the `scroll` event.
* Therefore, it has been modified to prevent the `wheel` event from automatically generating the `scroll` event, and to force the `scroll` event to occur by assigning the scroll value of the target element.
**As-Is**
**To-Be**
---

fix: flickering rows when mouse wheel scroll

---

packages/toast-ui.grid/src/dispatch/filter.ts

Fixed an issue where the `input` element of a filter was not initialized when cleared without applying the filter.
Unlike the `data` in the store, the `filterLayerState` is not observable. However, the TOAST UI Grid does not unfilter when no filter is applied. After all, the filter in the data does not change, so resetting the `filterLayeState` does not trigger a re-render.
To properly reflect a resetting `filterLayerState`, I've changed it to call a `notify` function to notify that the store has changed, causing a re-render.
---

fix: filter input not reset on clear filter

---

packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/keyboard.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/types/dataSource/index.d.ts

Improved performance of the setRows API.
1. modified to only make data within the viewport responsive, not all data set by setRows.
2. modified to update summaryData after all data is set, rather than updating summaryData for each row that is set.
3. modifiedDataManager to handle modified data as an array.
This should result in the following performance improvements
Test environment: macOS Ventura 13.1, Chrome 110, 1 million data (10000 rows, 100 columns), using summaryData for all columns
1. using the setRow API: 3,586,784 ms on average (about 1 hour)
2. using setRows API (before performance improvements): 595,712 ms on average (about 10 minutes) 
3. using the setRows API (after performance improvements): 595 ms on average (about 0.6 seconds)
This is a 6028x performance improvement over …

perf: improve performance of setRows

---

packages/toast-ui.grid/src/dispatch/rowSpan.ts
packages/toast-ui.grid/src/store/data.ts

* Fixed a problem that does not work correctly when row span is 1.
* This was caused by trying to apply row span to the next row even though rowSpan was 1.
---

fix: not work correctly when the row span is 1 (fix #1767)

---

packages/toast-ui.grid/cypress/integration/tree.spec.ts
packages/toast-ui.grid/src/dispatch/tree.ts
packages/toast-ui.grid/src/helper/observable.ts
packages/toast-ui.grid/src/view/bodyRow.tsx
packages/toast-ui.grid/src/view/bodyRows.tsx

* Improved performance when expanding/collapsing in a tree grid of large data.
* Improved rendering performance by preventing the rendering of child rows that are collapsed and therefore invisible.
* Previously, it rendered more than the number of collapsed child rows * the number of columns.
* When collapsing a tree, unobserve the tree property of child rows to avoid unnecessarily performing observable data behavior later on.
* It gave about a 2000x performance improvement.(from about 300000ms to about 150ms)
* Test environment
* Large children data: 10000 rows, 50 columns
* Make all child row to observable by scroll to bottom.
* M1 Pro, 16GB, Mac OS 13.1, Chrome 113
---

perf: large data with tree grid

---

packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts
packages/toast-ui.grid/src/helper/common.ts

* Fixed an issue where update history in DataManger was missing when using the setRows API.
* This issue was caused by two mistakes.
1. To efficiently update the update history, when looking for consecutive row indices, we checked for consecutive using the object itself, not the `rowIndex` property of the `IndexedRow` object.
2. When removing old update history using consecutive rowIndexes of the rows being updated, the starting index was set without considering the number of previously deleted elements, resulting in incorrectly deleting old update history.
---

fix: missing update history in DataManger

---

packages/toast-ui.grid/cypress/integration/data.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts

* Fixed an issue where using the setRows API when filtering would change the wrong row and create duplicate rows.
* It was caused by looking for the row index of the row to be changed in unfiltered data and finding the wrong row index.
**As-Is**
**To-Be**
---

fix: replace wrong rows when use setRows API with filter

---

packages/toast-ui.grid/cypress/integration/filter.spec.ts
packages/toast-ui.grid/src/dispatch/filter.ts

* Fixed an issue where all rows for the current filter would disappear while filtering, and then applying another filter would cause the filter to be applied incorrectly.
* It was caused by filter condition which disappeared due to data changes remaining in the filter state 
**As-Is**
**To-Be**
---

fix: set wrong select filter when previous filter data disappear by replacing

---

packages/toast-ui.grid/src/helper/dom.ts
packages/toast-ui.grid/src/view/bodyArea.tsx

* Fixed an issue where parent elements could not be scrolled when the cursor was above the grid.
* This was caused by calling `preventDefault` regardless of whether the grid was scrollable or not.
**As-Is**
**To-Be**
---

fix: parent elements could not be scrolled when cursor above the grid

---

packages/toast-ui.grid/cypress/integration/column.spec.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/store/column.ts
packages/toast-ui.grid/src/view/columnHeader.tsx
packages/toast-ui.grid/src/view/headerCheckbox.tsx
packages/toast-ui.grid/types/renderer/index.d.ts
packages/toast-ui.grid/types/store/column.d.ts

* Added custom header functionality.
* You can set a variety of HTML elements in the header, including images, icons, and more.
**To-Be**
---

feat: custom header by passing html element

---

packages/toast-ui.grid/cypress/integration/keyMap.spec.ts
packages/toast-ui.grid/src/dispatch/keyboard.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/helper/keyboard.ts
packages/toast-ui.grid/src/store/create.ts
packages/toast-ui.grid/src/store/focus.ts
packages/toast-ui.grid/src/view/clipboard.tsx
packages/toast-ui.grid/src/view/editingLayer.tsx
packages/toast-ui.grid/types/options.d.ts
packages/toast-ui.grid/types/store/focus.d.ts

The `moveDirectionOnEnter` option now allows you to determine the direction of focus movement when the Enter key is pressed. Possible move directions are `nextCell`, `prevCell`, `up`, and `down`.
**`nextCell`**
It is same behavior as when the Tab key is pressed.
**`prevCell`**
It is same behavior as when the Shift-Tab key is pressed.
**`up`**
It is similar behavior as when the Arrow up key is pressed. The difference is that it also acts while editing (finishes editing), and will automatically start editing if the cell to get focus is an editable cell.
**`down`**
It is similar behavior as when the Arrow down key is pressed. The difference is that it also acts while editing (finishes editing), and will automatically start editing if the cell to get focus is an editable cell.
---
Thank you …

feat: define move direction on enter

---

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/types/event/index.d.ts

Fixed an issue where multiple checks/unchecks using shift-click did not raise the check/unchecked event. 
When an event is fired due to a single checkbox click, the event handler is passed the same arguments as before, but when an event is fired due to a multiple checkbox check, the event handler is passed `rowKeys` as an argument, which is an array containing all rowKeys instead of `rowKey`.
---

fix: check/uncheck event emitted when multi check/uncheck via shift click

---

packages/toast-ui.grid/cypress/helper/util.ts
packages/toast-ui.grid/cypress/integration/keyMap.spec.ts
packages/toast-ui.grid/src/view/clipboard.tsx

Fixed to start editing in the current cell when the enter key is pressed in a cell that has been edited while using the `moveDirectionOnEnter` option.
**As-Is**
**To-Be**
---

fix: move focus on enter regardless cell editable

---

packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/types/options.d.ts

Added `beforeCheckBetween` event to prevent consecutive checkbox clicks with shift-click. If this is prevented, it will behave the same as normal click behavior(just check or uncheck).
```js
grid.on('beforeCheckBetween`, (e) => e.stop());
```
and added `rowKey` of click row checkbox argument on `checkBetween` event. The `rowKey` is the RowKey of the currently clicked row, which is only useful if the click is with the mouse.
---

feat: improve check between

---

packages/toast-ui.grid/cypress/integration/validation.spec.ts
packages/toast-ui.grid/src/grid.tsx
packages/toast-ui.grid/src/query/validation.ts

Added the ability to validate only for certain specified rows.
Passing an array of rowKeys as an argument to the `validate` API will validate only those rows that correspond to the given rowKeys. But validations that should be performed on all rows, such as unique, may not work correctly.
---

feat: validate on specific rows

---

packages/toast-ui.grid/cypress/integration/validation.spec.ts
packages/toast-ui.grid/src/dispatch/sort.ts
packages/toast-ui.grid/src/helper/observable.ts

Fixed an issue where using the `validate` API with sorting would result in an error.
This was caused by creating the viewDate directly from rawData without unobserving the rows that disappear outside the viewport when sorting.
This caused an error because it thought it was a row that was observable when in fact it was not, and did not convert it to observable.
---

fix: occur error when call validate with sort

---

packages/toast-ui.grid/cypress/integration/combinedFeatureTest.spec.ts
packages/toast-ui.grid/src/dispatch/data.ts
packages/toast-ui.grid/src/dispatch/focus.ts
packages/toast-ui.grid/src/dispatch/sort.ts
packages/toast-ui.grid/src/query/clipboard.ts
packages/toast-ui.grid/src/query/data.ts
packages/toast-ui.grid/src/query/validation.ts

Fixed an issue where editing could not be performed after sorting.
In the previous fix, i unobserved all data after sorting. However, i found additional issues where the next behavior did not work as intended (changing the data in the viewport to observable data).
Therefore, we discarded the previous fix and proceeded with a fix that proactively changes the rows that were previously observable data and the rows that are included in the viewport after sorting to observable data.
---

fix: cannot edit after sort

---

packages/toast-ui.grid/cypress/integration/keyMap.spec.ts
packages/toast-ui.grid/src/dispatch/keyboard.ts
packages/toast-ui.grid/src/view/editingLayer.tsx

Fixed an issue where typing Enter in the last cell (when there are no more cells to move) would not complete the edit when using the `moveDirectionOnEnter` option.
**As-Is**
**To-Be**
Fixed an issue where typing Enter in the last cell (when there are no more cells to move) would not complete the edit when using the `moveDirectionOnEnter` option.
---

fix: finish editing when type enter from last cell when using moveDirectionOnEnter
