nhn/tui.grid

src/js/event/keyEvent.js
=> feat: add backspace key information on key event model (close #86)

examples/example10-using-net.html, src/js/model/renderer.js
=> fix: rowNum is initialized when using pagination (close #98)

src/js/common/constMap.js, src/js/model/data/columnModel.js, src/js/model/data/extraDataManager.js, src/js/model/data/row.js, src/js/model/data/treeRow.js, src/js/model/data/treeRowList.js, src/js/model/manager.js, src/js/model/row.js, test/unit/js/model/data/columnModel.spec.js, test/unit/js/model/data/treeRow.spec.js, test/unit/js/model/data/treeRowList.spec.js
add data/view models
not yet completed.
---
=> feat: add tree models

src/js/model/data/treeRow.js, src/js/model/data/treeRowList.js, src/js/model/row.js, test/unit/js/model/data/treeRow.spec.js, test/unit/js/model/data/treeRowList.spec.js
add missing helper functions on models. #116 
---
=> feat: add model helpers

src/js/grid.js, src/js/model/data/rowList.js, src/js/model/data/treeRow.js, src/js/model/data/treeRowList.js, test/unit/js/model/data/treeRowList.spec.js
`append`, `removeRow` 이름 일관성 없음 리팩토링 필요.
=> feat: add api for append/remove rows

src/js/grid.js, src/js/model/data/treeRowList.js, src/js/model/row.js, test/unit/js/grid.spec.js, test/unit/js/model/data/treeRowList.spec.js, test/unit/js/model/row.spec.js
`descendent` -> `descendant` 오타 수정했습니다.
관련되어있는 녀석들 모두 수정해서 코드 확인할 필요 있어요.
---
=> feat: add api for checkbox

src/js/painter/treeCell.js
=> fix: change variable name from leafRow to lastChildRow

test/unit/js/grid.spec.js, test/unit/js/model/data/treeRow.spec.js, test/unit/js/model/data/treeRowList.spec.js, test/unit/js/model/row.spec.js
* 테스트 케이스에서 `done` 사용으로 인한 타임아웃 에러 발생
---
=> fix: failed on ie8 when running testcase

src/js/model/data/treeRow.js, src/js/model/data/treeRowList.js, test/unit/js/model/data/treeRow.spec.js, test/unit/js/model/data/treeRowList.spec.js
given parent's children were not updating properly when the parent had no children.
---
=> fix: not updating children

src/js/model/data/treeRowList.js
=> feat: add logic to use radio button when using tree

src/css/tree.styl, src/js/common/classNameConst.js, src/js/model/row.js, src/js/painter/treeCell.js, test/unit/js/painter/treeCell.spec.js
* 디자인에서 트리 라인 제거됨
* 계산 로직 이슈 있음
* 라인 엘리먼트 네이밍 변경 (`line` -> `depth`)
---
=> feat: remove connection line on tree column

src/js/model/selection.js, test/unit/js/model/selection.key.spec.js
* 버그 픽스 : 숨김 행이 있을 때 키 셀렉션이 정상적으로 동작하지 않음, 키 up/down 동작 값 구하는 로직 변경
---
=> fix: change logic to calculate value of key up and down

src/js/model/selection.js, test/unit/js/model/selection.key.spec.js
* 버그 픽스 : 로우 헤더 영역을 선택했을 때 행 전체가 아닌 셀이 선택됨
---
=> fix: the rows are not selected when selecting row headers

src/js/painter/treeCell.js
=> fix: not change value of tree data after editing

src/js/model/selection.js
=> fix: change wrong private property name (fix #167)

README.md
=> chore: update reamde contents

README.md
=> chore: change word from widget to component

src/css/layout.styl
* 서머리 영역 생성되었을 때 여백 발생 및 처리
---
=> fix: edit margin-top value of summary

src/js/grid.js, src/js/model/data/rowList.js, test/unit/js/grid.spec.js, test/unit/js/model/data/rowList.simple.spec.js
=> fat: add function type parameter on findRows (close #199)

examples/example08-using-datepicker.html, examples/example10-using-net.html
=> chore: change cdn url from rawgit to toast cdn

src/js/addon/net.js, test/unit/js/addon/net.spec.js
APIs
```js
// readData
grid.use('Net', {
...
withCredentials: true
});
// createDate, updateData, deleteData, modifyData
net.request('createData', {
withCredentials: true
});
```
---
=> feat: add withCredentials option (close #220)

package.json, webpack.config.js
=> feat: add config to create bundle file including jquery (close #250

src/js/painter/controller.js, test/unit/js/painter/controller.spec.js
=> fix: validation.dataType does not work (fix #203)

src/js/painter/cell.js
=> fix: (add/remove)CellClassName does not work (fix #255)

src/js/event/dragEventEmitter.js
=> fix: prevent dragmove when mouse button is not pressed (fix #253)

src/js/model/data/rowList.js, test/unit/js/addon/net.spec.js
=> fix: use checkedOnly options only when button column exists (fix #231)

index.d.ts, test/types/tsconfig.json
- Change type export to default export
=> chore: change type export to default export

src/js/grid.js, src/js/model/dimension.js, test/unit/js/grid.spec.js, test/unit/js/model/dimension.simple.spec.js
=> fix: unexpected change of fixedHeight (fix #269)

README.md, src/js/common/util.js, src/js/model/focus.js, src/js/model/manager.js
#266 
* 모바일 브라우저가 아닌경우 focusClipboard 이벤트 발생 막기
---
=> fix: prevent focus clipboard event when using mobile browser (#266)

src/js/grid.js, src/js/model/data/columnModel.js, test/unit/js/model/data/columnModel.spec.js
* api example
```js
grid.setColumnsTitle({
name: 'new name',
artist: 'new artist',
release: 'new release',
genre: 'new genre'
});
```
---
=> feat: add setColumnsTitle api

src/js/model/renderer.js
=> fix: set scroll after column model change

README.md, index.d.ts
=> Fix: change exporting types

test/types/type-tests.ts
=> chore: change type-tests.ts file import

src/js/grid.js, src/js/view/factory.js, src/js/view/layout/frame.js, src/js/view/layout/header.js, test/unit/js/grid.spec.js, test/unit/js/view/layout/header.spec.js
* Needs to dynamically change the complex column in header.
* Add `setHeader` api.
* test code
```js
grid.setHeader({
complexColumns: [
{
title: 'Basic',
name: 'mergeColumn1',
childNames: ['name', 'artist']
},
{
title: 'Extra',
name: 'mergeColumn2',
childNames: ['type', 'release', 'genre']
},
{
title: 'Detail',
name: 'mergeColumn3',
childNames: ['mergeColumn1', 'mergeColumn2']
},
{
title: 'Count',
name: 'mergeColumn4',
childNames: ['downloadCount', 'listenCount']
},
{
title: 'Album Info1',
name: 'mergeColumn5',
childNames: ['mergeColumn4']
}
]
});
```
---
=> feat: add setHeader public api

src/dispatch/viewport.ts, src/grid.tsx, src/store/dimension.ts, src/view/bodyArea.tsx, src/view/clipboard.tsx, src/view/headArea.tsx, stories/focus.stories.ts
=> feat: scroll follow focus

docs/README.md, docs/applying-themes.md, docs/binding-to-remote-data.md, docs/complex-columns.md, docs/custom-event.md, docs/getting-started.md, docs/input-types.md, docs/relation-between-columns.md, docs/using-date-picker-component.md, docs/using-summary.md, docs/v3.0.0-migration-guide-kor.md, docs/v3.0.0-migration-guide.md
- update links : nhnent -> nhn
=> doc: update link containing nhnent to nhn

cypress/integration/summary.spec.ts, src/dispatch/create.ts, src/dispatch/summary.ts, src/grid.tsx, src/helper/summary.ts, src/store/create.ts, src/store/dimension.ts, src/store/summary.ts, src/store/types.ts, src/types.d.ts, src/view/container.tsx, src/view/leftSide.tsx, src/view/rightSide.tsx, src/view/summaryArea.tsx, src/view/summaryBodyCell.tsx, src/view/summaryBodyRow.tsx, stories/summary.stories.ts
**Summary**
* Added
* Summary components and Types
* Store and Dispatch
* Story
* Cypress test
* Summary helper
* setSummaryColumnContent API
* Modifed
* SummaryArea in leftSide and rightSide components
* css related summary position in container component
* Summary options in dimension store
---
=> feat: summary area

src/editor/checkbox.ts, src/editor/manager.ts, src/editor/select.ts, src/editor/text.ts, src/editor/types.d.ts, src/grid.tsx, src/instance.ts, src/store/columns.ts, src/store/summary.ts, src/store/types.ts, src/types.d.ts, src/view/bodyCell.tsx, src/view/editingLayer.tsx, src/view/editingLayerInner.tsx, src/view/root.tsx, stories/column.stories.ts, stories/editor.stories.ts, stories/summary.stories.ts
- [] Docs have been added/updated (for bug fixes/features)
- [] It does not introduce a breaking change or has description for the breaking change
- Change editor / editorOptions API
---
=> feat: change column editor options spec

.eslintrc.js, src/dispatch/data.ts, src/dispatch/keyboard.ts, src/grid.tsx, src/helper/common.ts, src/helper/dom.ts, src/i18n/index.ts, src/store/focus.ts, src/store/viewport.ts, src/theme/cssRuleBuilder.ts, src/theme/manager.ts, src/view/bodyArea.tsx, src/view/selectionLayer.tsx
=> refactor: remove es6 methods

cypress/integration/sort.spec.ts, src/dispatch/data.ts, src/grid.tsx, src/helper/common.ts, src/helper/sort.ts, src/store/columns.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, src/view/editingLayerInner.tsx, src/view/headArea.tsx, stories/sort.stories.ts
**Sort**
* Added
* sortOptions type
* reactive sortOptions data in data store
* sort, unSort, getSortState api
* example story
* cypress test
* sort helper
* Modified
* headArea, editingLayerInner for sorting
* data dispatcher for Sorting
---
=> feat: sort

src/dispatch/data.ts, src/dispatch/keyboard.ts, src/grid.tsx, src/helper/browser.ts, src/helper/clipboard.ts, src/helper/common.ts, src/helper/keyboard.ts, src/query/clipboard.ts, src/query/keyboard.ts, src/store/columns.ts, src/store/create.ts, src/store/focus.ts, src/store/selection.ts, src/store/types.ts, src/types.d.ts, src/view/clipboard.tsx, stories/clipboard.stories.ts, stories/focus.stories.ts
=> feat: add clipboard api

src/dispatch/data.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts
=> refactor: add RowAttribute prop

cypress/integration/validation.spec.ts, src/dispatch/data.ts, src/grid.tsx, src/helper/clipboard.ts, src/helper/common.ts, src/query/validation.ts, src/store/columns.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, src/view/bodyCell.tsx, stories/validation.stories.ts
* Set options
```js
gridOptions = {
columns: [
{
name: 'c1',
...
required: true, // default: false
dataType: 'string' // or 'number'
}
]
};
```
* API
```js
/**
* // return value example
* [
*     {
*         rowKey: 1,
*         errors: [
*             {
*                 columnName: 'c1',
*                 errorCode: 'REQUIRED'
*             },
*             {
*                 columnName: 'c2',
*                 errorCode: 'REQUIRED'
*             }
*         ]
*     },
*     {
*         rowKey: 3,
*         errors: [
*             {
*                 columnName: 'c1',
*                 errorCode: 'TYPE_STRING' // add on v4.0
*             },
*             {
*                 columnName: 'c2',
*                 errorCode: 'TYPE_NUMBER'
*             }
*         ]
*     }
* ]
*/ …
```
=> feat: add validation

.eslintrc.js, cypress/integration/columnOptions.spec.ts, cypress/integration/data.spec.ts, cypress/integration/index.spec.ts, cypress/support/commands.js, cypress/support/index.d.ts, src/dispatch/data.ts, src/grid.tsx, src/helper/common.ts, src/helper/reactive.ts, src/store/columns.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, src/view/container.tsx, src/view/hoc.tsx
- `watch()` returns `unwatch()` function 
- Added `notify()` which invoke handlers manually
- Added `appendRow()` and `prependRow`() API
---
=> feat: appendRow / prependRow

src/formatter/listItemText.ts, src/store/data.ts, stories/editor.stories.ts
- Builtin Formatter (listItemText)
---
=> feat: add listItemText formatter (builtin)

src/dispatch/data.ts
=> refactor: classname

cypress/integration/data.spec.ts, src/dispatch/data.ts, src/dispatch/dimension.ts, src/helper/common.ts, src/helper/observable.ts, src/store/create.ts, src/store/dimension.ts, src/store/rowCoords.ts, src/store/types.ts, src/store/viewport.ts, src/view/bodyArea.tsx, src/view/bodyCell.tsx, src/view/bodyRow.tsx, src/view/bodyRows.tsx, src/view/container.tsx, stories/dimension.stories.ts
- support `rowHeight: auto` / `bodyRowHeight: auto` options
- change heights array according to data.rawData[x]._attributes.height
---
=> feat: auto row height, append/remove heights

cypress/integration/eventBus.spec.ts, cypress/integration/summary.spec.ts, src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/keyboard.ts, src/dispatch/mouse.ts, src/dispatch/selection.ts, src/event/eventBus.ts, src/event/gridEvent.ts, src/eventBus.ts, src/grid.tsx, src/helper/common.ts, src/helper/dom.ts, src/helper/selection.ts, src/instance.ts, src/store/focus.ts, src/store/types.ts, src/theme/manager.ts, src/theme/preset.ts, src/view/container.tsx
* 마우스 이벤트 반환 값 중 targetType값 변경
* rowHead -> rowHeader
* columnHead -> columnHeader
* 기존
```
targetType: 'rowHead' | 'columnHead' | 'dummy' | 'cell' | 'etc';
```
* 변경
```
targetType: 'rowHeader' | 'columnHeader' | 'dummy' | 'cell' | 'etc';
```
---
=> feat: eventbus

cypress/integration/editor.spec.ts, src/dispatch/data.ts, src/event/gridEvent.ts, src/store/types.ts, src/types.d.ts
=> feat: onBeforeChange, onAfterChange

src/dispatch/keyboard.ts, src/dispatch/mouse.ts, src/store/types.ts, src/view/bodyArea.tsx
=> refactor: set selection start cell properly, block rowheader select, focus

cypress/integration/data.spec.ts, src/dispatch/data.ts, src/dispatch/focus.ts, src/grid.tsx, src/query/data.ts, src/query/focus.ts, src/store/create.ts, src/store/focus.ts, src/store/types.ts, src/types.d.ts, src/view/container.tsx, stories/editor.stories.ts, stories/focus.stories.ts
- startEditing
- startEditingAt
- getColumns
- getColumnValues
- getIndexOfColumn
- setColumnValues
- activateFocus
---
=> feat: extra APIs

src/store/columnCoords.ts, src/store/create.ts, src/store/dimension.ts, src/view/bodyArea.tsx, src/view/container.tsx, src/view/rightSide.tsx
=> feat: add scrollX, scrollY option

src/dispatch/data.ts, src/helper/common.ts, src/store/columns.ts, src/store/create.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, src/view/bodyCell.tsx, src/view/container.tsx, stories/column.stories.ts
- Add `keyColumnName` options
- Fix IE9 issues 
- `requestAnimationFrame` -> `setTimeout`
- remove `Array.prototype.findIndex`
---
=> feat: keyColumnName / fix: IE9 issues

src/view/bodyArea.tsx
=> fix: apply page offset when dispatch mouse event

package-lock.json, package.json, src/css/grid.css, webpack.config.js
- Extract CSS file from bundle JS.
=> chore: extract css from bundle

src/dispatch/mouse.ts, src/store/columnCoords.ts, src/store/types.ts, src/store/viewport.ts, src/view/bodyArea.tsx, src/view/bodyRows.tsx, src/view/colGroup.tsx, src/view/headerArea.tsx, src/view/summaryArea.tsx, stories/attributes.stories.ts
=> feat: virtual-scroll for columns

cypress/integration/tree.spec.ts, src/dispatch/data.ts, src/dispatch/tree.ts, src/grid.tsx, src/helper/tree.ts, src/query/data.ts, src/query/tree.ts, src/store/column.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, src/view/bodyRow.tsx, src/view/treeCellContents.tsx, stories/tree.stories.ts
```js
{
treeColumnOptions: {
name: 'c1',
useCascadingCheckbox: true // default
}
}
```
* Add tree column options on columns store.
---
=> feat: add cascading checkbox

src/dispatch/mouse.ts, src/helper/dom.ts, src/view/bodyArea.tsx, src/view/bodyCell.tsx, src/view/headerArea.tsx, stories/selection.stories.ts
=> feat: selection header

cypress/integration/tree.spec.ts, src/dispatch/tree.ts, src/helper/tree.ts, src/store/data.ts, src/store/types.ts, src/view/treeCellContents.tsx
* appendRow
```js
appendTreeRow({ c1: foo }); // on root
appendTreeRow({ c1: foo }, { parentRowKey: 1 });
```
* removeRow
```js
removeRow(parentRowKey);
```
---
=> feat: add appendRow and removeRow api

cypress/.eslintrc.js, webpack.config.js
=> chore: fix eslint rules / add externals

cypress/integration/column.spec.ts, cypress/integration/data.spec.ts, cypress/integration/dataSource.spec.ts, cypress/integration/dimension.spec.ts, cypress/integration/dom.spec.ts, cypress/integration/sort.spec.ts, cypress/integration/summary.spec.ts, cypress/support/commands.js, src/dispatch/column.ts, src/event/gridEvent.ts, src/grid.tsx, src/helper/dom.ts, src/store/column.ts, src/store/columnCoords.ts, src/store/data.ts, src/store/dimension.ts, src/store/types.ts, src/view/bodyCell.tsx, src/view/bodyDummyRow.tsx, src/view/bodyRow.tsx, src/view/bodyRows.tsx, src/view/colGroup.tsx, src/view/columnResizer.tsx, src/view/container.tsx, src/view/headerArea.tsx, src/view/rightSide.tsx, src/view/summaryBodyCell.tsx, webpack.config.js
- `setColumns`
- `resetColumnWidhts`
- `getElements`
- Remove `Attributes` data types -> Add `dataAttr` constant map
- Column widths calculation (regarding cell-border width)
- Set external libraries to `wepback.config.js` only for production build 
---
=> feat: setColumns / resetColumnWidths / getElement

src/dispatch/keyboard.ts, src/query/keyboard.ts, src/view/clipboard.tsx
=> feat: remove content

cypress/integration/rowSpan.spec.ts, src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/keyboard.ts, src/dispatch/mouse.ts, src/dispatch/selection.ts, src/grid.tsx, src/helper/common.ts, src/helper/rowSpan.ts, src/helper/selection.ts, src/query/keyboard.ts, src/store/data.ts, src/store/focus.ts, src/store/selection.ts, src/store/types.ts, src/store/viewport.ts, src/types.d.ts, src/view/bodyCell.tsx, src/view/bodyRow.tsx, src/view/rowSpanCell.tsx, stories/rowSpan.stories.ts
**rowSpan**
* calculate rowSpan index or position when focus, selection, virtual scrolling
* update rowSpan when append or remove row
* store rowSpan data in `rowSpanMap`, not `_attribute`
* rowSpanCell component
* getRowSpanData() API
* storybook(`visual test - selection, focus, virtual scrolling`)
* cypress test(`API test`)
###TODO
* next cell index related rowSpan in keyboard selection
* multi sort when calls unsort API
###DEMO
* http://10.78.9.214:6006/?path=/story/rowspan--rowspan
---
=> feat: row span

src/store/column.ts, src/store/create.ts, src/store/dimension.ts, src/store/types.ts, src/types.d.ts, src/view/complexHeader.tsx, src/view/headerArea.tsx, src/view/headerCheckbox.tsx, src/view/sortingButton.tsx, stories/complexColumns.stories.ts
* Set options
```js
const complexColumns = [
{
header: 'Basic',
name: 'mergeColumn1',
childNames: ['name', 'artist']
},
{
header: 'Extra',
name: 'mergeColumn2',
childNames: ['type', 'release', 'genre']
},
{
header: 'Detail',
name: 'mergeColumn3',
childNames: ['mergeColumn1', 'mergeColumn2']
},
{
header: 'Count',
name: 'mergeColumn4',
childNames: ['downloadCount', 'listenCount']
},
{
header: 'Album Info',
name: 'mergeColumn5',
childNames: ['price', 'mergeColumn3', 'mergeColumn4']
}
];
const options = {
header: {
height: 40, // default
complexColumns: complexColumns
}
}
```
* Separate **header checkbox** and **sorting button** component on header area.
* http://localhost:6006/?path=/story/complex-columns--complex-columns
* Selection
* Resize handler
* Cypress test
---
Thank you for your …
=> feat: add complex columns

cypress/integration/data.spec.ts, src/grid.tsx, src/helper/common.ts, src/query/data.ts, stories/editor.stories.ts
=> feat: find rows

samples/relations.ts, src/grid.tsx, src/store/data.ts
* add resetOriginData() API
* fix to initialize relation column value when parent column value is chenged
---
=> fix: relation value

cypress/integration/data.spec.ts, cypress/integration/tree.spec.ts, src/grid.tsx
```js
removeCheckedRows();
// or use confirm message
removeCheckedRows(true);
```
---
=> feat: add removeCheckedRows api

cypress/integration/dataSource.spec.ts, cypress/integration/eventBus.spec.ts, cypress/integration/tree.spec.ts, src/store/column.ts, src/types.d.ts, stories/attributes.stories.ts, stories/complexColumns.stories.ts, stories/dummyRows.stories.ts, stories/rowHeaders.stories.ts, stories/selection.stories.ts, stories/tree.stories.ts
```js
rowHeaders: ['_number', '_checked'];
rowHeaders: [
{
type: '_number',
...
}
];
```
```js
rowHeaders: ['rowNum', 'checkbox'];
rowHeaders: [
{
type: 'rowNum',
...
}
];
```
---
=> fix: change type of row headers option

src/dispatch/mouse.ts, stories/rowSpan.stories.ts
* fix selection start point when has frozen count option
* change row span story name
---
=> fix: frozen count selection

src/helper/column.ts, src/store/column.ts, src/store/data.ts, src/view/bodyCell.tsx, src/view/complexHeader.tsx, src/view/headerArea.tsx
=> feat: add helper method to check checkbox or row number column

src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/keyboard.ts, src/dispatch/mouse.ts, src/dispatch/selection.ts, src/helper/rowSpan.ts, src/query/keyboard.ts, src/store/focus.ts, src/store/viewport.ts
* fix rowSpan selection in up, down command
* change enableRowSpan parameter
---
=> fix:row span selection

src/dispatch/data.ts, src/editor/checkbox.ts, src/editor/datePicker.ts, src/editor/select.ts, src/editor/text.ts, src/editor/types.d.ts, src/formatter/listItemText.ts, src/helper/clipboard.ts, src/renderer/default.ts, src/renderer/rowHeaderInput.ts, src/renderer/types.d.ts, src/store/column.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, src/view/bodyCell.tsx, src/view/editingLayerInner.tsx, stories/editor.stories.ts, stories/renderer.stories.ts, stories/rowHeaders.stories.ts
- editor / editorOptions -> editor.type / editor.options
- renderer / rendererOptions -> renderer.type / renderer.options
---
=> feat: custom editor/renderer spec changes

src/dispatch/mouse.ts, src/helper/column.ts, src/query/mouse.ts, src/query/selection.ts, src/store/selection.ts, src/view/complexHeader.tsx, src/view/headerArea.tsx
=> feat: complex header selection

src/css/grid.css, src/helper/keyboard.ts, src/query/keyboard.ts, src/store/selection.ts
=> fix: tree keyboard selection

docs/COMMIT_MESSAGE_CONVENTION.md, docs/ISSUE_TEMPLATE.md, docs/PULL_REQUEST_TEMPLATE.md, docs/README.md, docs/applying-themes.md, docs/binding-to-remote-data.md, docs/complex-columns.md, docs/custom-event.md, docs/getting-started.md, docs/input-types.md, docs/relation-between-columns.md, docs/using-date-picker-component.md, docs/using-summary.md, docs/v3.0.0-migration-guide-kor.md, docs/v3.0.0-migration-guide.md
=> chore: add exist docs file

cypress/integration/sort.spec.ts, src/grid.tsx, src/view/complexHeader.tsx, stories/rowSpan.stories.ts, stories/selection.stories.ts, stories/sort.stories.ts
* `unSort` -> `unsort`
* `seleciton` -> `setSelectionRange`
---
=> chore: change method name

package.json, src/editor/datePicker.ts, src/view/pagination.tsx, webpack.config.js
=> chore: add minified argument for build script

cypress/integration/column.spec.ts, src/dispatch/column.ts, src/dispatch/dimension.ts, src/grid.tsx, src/types.d.ts
=> feat: setHeader api

src/store/viewport.ts
* add rowCalculation parameter for proper calculation
---
=> fix: calculateRange

cypress/integration/column.spec.ts, src/dispatch/data.ts, src/grid.tsx
=> feat: setColumHeaders

src/grid.tsx, src/theme/manager.ts, src/theme/preset.ts, src/theme/styleGenerator.ts, src/types.d.ts, stories/theme.stories.ts
=> chore: head -> header / rowHead -> rowHeader

src/store/column.ts, src/types.d.ts
=> fix: add resizable columnOptions

cypress/integration/datePicker.spec.ts, src/editor/datePicker.ts, src/store/column.ts
=> fix: apply changed options

src/view/headerArea.tsx, stories/rowHeaders.stories.ts
=> fix: change logic to prevent event on sorting button

src/i18n/index.ts, src/store/viewport.ts
* check emptiness of rawData when calculateRange with rowSpan
* return empty string when text is undefined or null
---
=> fix:calculate range row span

src/grid.tsx, src/helper/googleAnalytics.ts, src/types.d.ts
=> feat: add google analytics

src/view/editingLayerInner.tsx
=> fix: editor left position

cypress/integration/relation.spec.ts, cypress/integration/summary.spec.ts, samples/relations.ts, src/dispatch/column.ts, src/editor/checkbox.ts, src/editor/select.ts, src/editor/types.d.ts, src/formatter/listItemText.ts, src/helper/editor.ts, src/store/column.ts, src/store/data.ts, src/store/viewport.ts
* add formatter option
* setColumns API
* modify custom renderer, editor for relation column
---
=> fix:custom editor

index.d.ts, src/grid.tsx
* modify type definition for v4.0
---
=> fix: type definition

src/dispatch/mouse.ts
=> fix: set focus when header click

cypress/integration/columnOptions.spec.ts, src/helper/clipboard.ts, src/renderer/default.ts, src/store/data.ts, src/store/types.ts, src/types.d.ts, stories/clipboard.stories.ts, stories/editor.stories.ts
=> feat: remove prefix/postfix options

src/view/complexHeader.tsx, src/view/headerArea.tsx
=> feat: add rowHeader class on header area

src/helper/column.ts, src/view/headerArea.tsx
=> fix: rowHeader checkbox click selection

src/dispatch/data.ts, src/editor/checkbox.ts, src/editor/datePicker.ts, src/editor/select.ts, src/editor/text.ts, src/editor/types.d.ts, src/store/column.ts, src/view/editingLayerInner.tsx
=> Fix: onChange eventbus

src/store/column.ts, src/view/focusLayer.tsx
=> fix: whitespace

samples/tree.ts, src/helper/tree.ts, src/view/treeCellContents.tsx
=> fix: change default state of exapnded button

src/view/bodyRow.tsx
=> fix: add border width on auto row height

src/dispatch/data.ts, src/helper/renderState.ts
* fix renderState when data rows are changed.
---
=> fix: renderState when data is changed

docs/README.md
=> docs: add link to migration guide

README.md, docs/custom-renderer.md
=> docs: change typo

docs/relation-between-columns.md, package.json
* version up
* remove nhnent keyword
* Example page -> Example
---
=> chore: version up

.gitignore, package.json, tuidoc.config.json
=> feat: update config files to generate docs

README.md, src/dispatch/tree.ts, src/event/gridEvent.ts, src/grid.tsx
* Add and change annotations
---
=> feat: add api annotations for docs

docs/complex-columns.md, examples/example01-basic.html, examples/example15-custom-event.html
=> docs: fix typo

README.md
=> chore: remove badge

README.md
=> chore: fix the example link

README.md
* add sentence for release
---
=> chore: add sentence for release

package.json
=> feat: include typescript declared file on package.json (close #472)

src/dataSource/gridAjax.ts
=> fix: modify typo in dataSource

index.d.ts, package.json
=> fix: add constructor type

src/view/complexHeader.tsx, src/view/headerArea.tsx, src/view/sortingButton.tsx
* fix to toggle the sort button when sorts the column.
---
=> fix: toggle sortable button

src/dispatch/viewport.ts
* fix scroll width, height in viewport when scrollX, scrollY option are false
---
=> fix: scroll width, height in viewport

src/js/model/selection.js
* fix scroll sticking(#478)
---
=> fix: stop auto scrolling when mouseup

src/js/model/renderer.js, test/unit/js/model/renderer.spec.js
=> fix: set correct height when remove row (fix #483)

src/js/view/layout/header.js
=> fix: create resize handler correctly (close #477)

package.json, tsBannerGenerator.ts, webpack.config.js
* add banner for bundle files and ts definition file in build script
---
=> chore: add banner script

cypress/integration/summary.spec.ts, src/store/summary.ts
* change summary values when reactive data rows are changed(#482 )
---
=> fix: summary reactivity

index.d.ts, src/js/common/constMap.js, src/js/grid.js, src/js/model/data/rowList.js, src/js/model/selection.js, src/js/view/layout/header.js, test/unit/js/view/layout/header.spec.js
* add sort option for changing initial sort(#479 )
---
=> feat: add sort option

src/dispatch/focus.ts, src/dispatch/selection.ts
=> chore: add focus change comment

src/js/painter/treeCell.js
=> fix: change global jquery to commonJS (fix #394)

src/store/column.ts
some column option is not applicable. because column Object not include  ellipsis, valign and defaultValue.
---
=> fix: not applied column options (#492)

src/view/editingLayerInner.tsx
* fixed that wrong left position of the editing layer due to multiplying the frozen count on calculating.
---
=> fix: modify wrong left position of the editing layer

cypress/integration/rowSpan.spec.ts, src/store/data.ts, stories/rowSpan.stories.ts
* fixed that calculating row span in case the specific row has multi row span.(#512 )
---
=> fix: multi row span

src/dispatch/column.ts, src/dispatch/data.ts, src/dispatch/keyboard.ts, src/dispatch/mouse.ts, src/dispatch/selection.ts, src/grid.tsx, src/helper/common.ts, src/helper/rowSpan.ts, src/query/clipboard.ts, src/query/keyboard.ts, src/query/selection.ts, src/store/column.ts, src/store/columnCoords.ts, src/store/dimension.ts, src/store/focus.ts, src/store/selection.ts, src/store/types.ts, src/store/viewport.ts, src/view/bodyArea.tsx, src/view/bodyRows.tsx, src/view/columnResizer.tsx, src/view/complexHeader.tsx, src/view/headerArea.tsx, src/view/summaryArea.tsx
**Fixed**
* selection
* fixed that keyboard selection with row headers.
* fixed that mouse selection with row headers.
* fixed that row header selection with row span.
* fixed that scroll sync in moving selection on mouse.
* clipboard
* fixed that clipboard copy and paste with row headers(#489 ).
* keyMap
* fixed that moving to first cell with row headers.
* fixed that moving to last cell with row headers.
* fixed that moving to first column with row headers.
* fixed that moving to last column with row headers.
* fixed that moving to first row.
* fixed that moving to last row.
* fixed that the selection range on pressing the  `ctrl + a`.
* summary
* fixed that the summary position with row headers.
* API
* fixed that `getIndexOfColumn()` method(filtering row header columns).
---
Thank you …
=> fix: selection, focus, clipboard for considering rowHeaders

package.json
* version up(4.0.3) in packge.json
---
=> chore: version up(4.0.3)

src/editor/datePicker.ts, src/grid.tsx, src/view/pagination.tsx
=> feat: add disabled GA option on dependencies (close #522)

package.json, src/view/colGroup.tsx, stories/attributes.stories.ts
* fixed that calculating column width when resizes the specific column(#516 ).
---
=> fix: sync column width

index.d.ts, package.json, src/js/common/constMap.js, src/js/grid.js, src/js/model/data/rowList.js, src/js/view/layout/header.js, test/unit/js/view/layout/header.spec.js
* change sort option to sortingType option(#479 ).
---
=> fix: change sort option to sortingType option

README.md, examples/example08-using-datepicker.html, package-lock.json, package.json, src/js/grid.js, src/js/view/datePickerLayer.js, src/js/view/factory.js, src/js/view/pagination.js
=> feat: add disabled GA option on dependencies (fix #522)

README.md
=> fix: edit text

README.md
=> fix: edit version of code snippet on readme

examples/css/tui-example-style.css, examples/example13-i18n.html, examples/example17-dummy-row.html, examples/example18-column-resize.html, examples/example19-sort.html, examples/example20-validation.html, tuidoc.config.json
=> docs: update example

package.json, tuidoc.config.json
=> chore: modify nhnent to nhn

cypress/integration/tree.spec.ts, src/view/bodyRow.tsx
* fixed the tree rendering performance(#505 )
---
=> fix: tree performance

docs/ko/README.md, docs/ko/width-height.md
* Add tutorial to set width and height value
* Preview : https://github.com/nhn/tui.grid/blob/feat/add-tutorial-width-height/docs/ko/width-height.md
---
=> feat: add tutorial to set width and height values

cypress/integration/eventBus.spec.ts, src/dispatch/data.ts, src/event/gridEvent.ts, src/view/sortingButton.tsx
=> feat: add sort gridEvent(#515)

.gitignore, cypress/integration/eventBus.spec.ts, package-lock.json, src/dispatch/mouse.ts, src/dispatch/selection.ts, src/store/selection.ts, src/store/types.ts
=> fix: shift selection bug(#535)

cypress/integration/dataSource.spec.ts, cypress/integration/sort.spec.ts, src/dispatch/data.ts, src/grid.tsx, src/helper/rowSpan.ts, src/helper/sort.ts, src/store/data.ts, src/store/types.ts, src/view/rowSpanCell.tsx, src/view/sortingButton.tsx
=> feat: sort cancel(#555)

cypress/integration/tree.spec.ts, examples/example14-tree.html, src/dispatch/tree.ts, src/grid.tsx, src/helper/tree.ts, src/types.d.ts
=> feat: add tree api to append and remove row (close #551)

docs/en/custom-event.md, docs/ko/custom-event.md
* Add the description for tree events on the document of custom event.
---
=> feat: add tree event on custom event document

docs/en/complex-columns.md, docs/en/relation-between-columns.md, docs/en/summary.md, docs/en/themes.md, docs/en/tree.md, docs/ko/custom-editor.md, docs/ko/data-source.md, docs/ko/frozen-columns.md, docs/ko/row-header.md, docs/ko/setting-width-height.md
=> docs: modify english tutorial

cypress/integration/editor.spec.ts, cypress/integration/relation.spec.ts, src/dispatch/column.ts, src/dispatch/focus.ts, src/dispatch/keyboard.ts, src/query/data.ts
*  cannot edit the value on disabled cell(#575 )
---
=> fix: cannot edit the value on disabled cell

package.json, src/grid.tsx, src/helper/keyboard.ts, src/store/data.ts, src/store/types.ts, src/view/editingLayerInner.tsx, src/view/rowSpanCell.tsx
* improve performance when scrolling(#568 )
* get row span through property of viewRow
---
=> fix: scroll performance

cypress/integration/eventBus.spec.ts, src/view/container.tsx
* fixed dblclick event typo(#580 )
---
=> fix: dblclick typo

cypress/integration/data.spec.ts, cypress/integration/lazyObservable.spec.ts, cypress/integration/tree.spec.ts, src/css/grid.css, src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/sort.ts, src/dispatch/tree.ts, src/helper/observable.ts, src/helper/tree.ts, src/store/create.ts, src/store/data.ts, src/view/bodyArea.tsx, src/view/hoc.tsx, stories/sort.stories.ts
* improve the performance for initial rendering with adding the lazy observable on rows of data
* modify focus layer z-index for sync the scrolling between left side and right side
---
=> feat: lazy observable

src/dispatch/mouse.ts, src/grid.tsx, src/store/selection.ts
=> feat: make available select by click(#567)

src/editor/datePicker.ts, src/editor/text.ts, src/view/editingLayerInner.tsx
fixed that editing cell has null value(#583)
---
=> fix: editing cell has null value

src/view/bodyRow.tsx
=> fix: compare with borderWidth(#541)

src/helper/browser.ts, src/view/clipboard.tsx, src/view/container.tsx
=> feat: support mobile focus, edit(#593)

cypress/integration/dataSource.spec.ts, src/dataSource/modifiedDataManager.ts, src/dataSource/serverSideDataProvider.ts, src/dataSource/types.d.ts, src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/mouse.ts, src/dispatch/tree.ts, src/grid.tsx, src/query/data.ts, src/query/tree.ts, src/store/create.ts, src/store/focus.ts, src/view/bodyCell.tsx, src/view/editingLayerInner.tsx
* improve the performance to find the index, row through rowKey applying binary search.
---
=> fix: improve the performance to find the index through rowKey

cypress/integration/eventBus.spec.ts, index.d.ts, src/dispatch/column.ts, src/dispatch/focus.ts, src/event/gridEvent.ts, src/grid.tsx, src/types.d.ts, src/view/container.tsx, src/view/root.tsx, tuidoc.config.json
* Add new custom event(#601 )
---
=> feat: add new custom event

index.d.ts
* fixed wrong type definition(#553)
---
=> fix: 3.8 type definition

src/js/model/data/treeRowList.js, test/unit/js/grid.spec.js
* fixed non-emitting tree expanded, collapsed event(#554)
* fixed emit tree expanded, collapsed event for the data of non-having children 
---
=> fix: 3.8 expanded event bug

cypress/integration/column.spec.ts, examples/example21-header-align.html, src/css/grid.css, src/dispatch/column.ts, src/helper/dom.ts, src/renderer/rowHeaderInput.ts, src/store/column.ts, src/store/create.ts, src/store/types.ts, src/types.d.ts, src/view/complexHeader.tsx, src/view/headerArea.tsx, stories/header.stories.ts, tuidoc.config.json
=> feat: header align(#587)

cypress/integration/data.spec.ts, cypress/integration/lazyObservable.spec.ts, src/store/data.ts, src/store/types.ts, src/view/bodyRows.tsx, src/view/hoc.tsx
* improve the observe and unobserve logic in hoc component when props are updated
---
=> fix: improve updating component performance

examples/example07-themes.html, package-lock.json, src/grid.tsx, src/helper/dom.ts, src/theme/manager.ts, src/theme/preset.ts, src/theme/styleGenerator.ts, src/types.d.ts, src/view/container.tsx, stories/theme.stories.ts
#610 
```js
Grid.applyTheme('custom', { 
row: { 
hover: { 
background: '#00eeff' 
},
even: {
background: '#00eeff' 
},
odd: {
background: '#00eeff' 
},
dummy: {
background: '#00eeff' 
}
}
});
```
* deprecate
* `extOptions.cell.currentRow`
* `extOptions.cell.evenRow`
* `extOptions.cell.oddRow`
* `extOptions.cell.dummy`
---
=> feat: row hover background(#610)

package.json
=> chore: fix test script

cypress/integration/eventBus.spec.ts, docs/en/custom-event.md, docs/ko/custom-event.md, src/dispatch/data.ts
=> feat: add uncheck, check gridEvent(#615)

src/dispatch/focus.ts, src/grid.tsx, src/helper/dom.ts, src/store/data.ts, src/view/container.tsx, src/view/editingLayerInner.tsx
* fixed row hover on mouseover header cell
* fixed getting the value through editor not store data when calls finishEditing method
---
=> fix:row hover on mouseover header cell

cypress/integration/eventBus.spec.ts, src/editor/datePicker.ts, src/grid.tsx, types/tui-date-picker/index.d.ts, webpack.config.js
* Added `destroy` API(#510 )
---
=> fix: add destroy api

cypress/integration/validation.spec.ts, docs/ko/validation.md, examples/example20-validation.html, index.d.ts, src/query/validation.ts, src/store/data.ts, src/store/types.ts, src/view/bodyCell.tsx
=> feat: extend validation type(#623)

cypress/integration/summary.spec.ts, src/dispatch/column.ts, src/dispatch/data.ts, src/dispatch/summary.ts, src/helper/summary.ts, src/store/summary.ts
* remove observe function in summary to improve the performance
---
=> fix: summary observer performance

cypress/integration/data.spec.ts, src/dispatch/data.ts, src/helper/observable.ts
=> fix: create wrong rowkey

src/grid.tsx, src/helper/tree.ts
* fixed that append tree row on wrong position
* fixed that tree rowKey is duplicated.
---
=> fix: append tree row on wrong position

cypress/integration/summary.spec.ts, src/dispatch/column.ts, src/dispatch/summary.ts, src/store/summary.ts, src/store/types.ts, src/view/summaryBodyCell.tsx
* fixed summary options for columns that doesn't exist
* prevent to calculate row header cell in summary
---
=> fix: summary option

docs/en/custom-editor.md, docs/en/custom-renderer.md, docs/en/row-span.md, docs/en/setting-width-height.md, docs/en/tree.md, docs/en/validation.md
=> docs: add en-tutorials

cypress/integration/data.spec.ts, src/dispatch/data.ts
* fixed that creates -infinity rowKey when appends row on empty grid.
---
=> fix: infinity row key

src/grid.tsx, src/helper/clipboard.ts, src/view/clipboard.tsx
* added selection range to clipboard to prevent IE access alert
---
=> fix: add selection to clipboard

karma.conf.js, package-lock.json, package.json, src/js/common/clipboardUtil.js, src/js/event/dragEventEmitter.js, src/js/grid.js, src/js/model/clipboard.js, src/js/view/clipboard.js, src/js/view/container.js
* added selection range to clipboard to prevent IE access alert
---
=> fix: clipboard access(v3.9)

src/css/grid.css
[Quotation marks in grid.css](https://github.com/nhn/tui.grid/blob/master/src/css/grid.css#L255) prevent some webpack packaging. This pull request address that issue.
=> fix: remove invalid quotes in css

index.d.ts, src/grid.tsx, src/types.d.ts, src/view/root.tsx
* changed `onGridBeforeDestroyed` to `onGridBeforeDestroy`
---
=> fix: change onGridBeforeDestroyed to onGridBeforeDestroy

package-lock.json, package.json
* added `tui-release-notes` dependency
---
=> chore: add tui-release-notes dependency

README.md, cypress/integration/editor.spec.ts, cypress/integration/eventBus.spec.ts, cypress/integration/sort.spec.ts, src/dispatch/focus.ts, src/dispatch/sort.ts, src/grid.tsx
* checked sortable property on calling sort API.
* checked editable, disabled property on calling startEditing, finishEditing API.
* considered the tree data on making observable the data
---
=> fix: check sortable on sort API and editable on startEditing, finishEditing API

cypress/integration/sort.spec.ts, samples/basic.ts, src/helper/sort.ts
Fixed numeric sort bug (Add type conversion)
related issues link: https://github.com/nhn/tui.grid/issues/687
---
=> fix: fixed numeric sort bug. (#687)

cypress/integration/dimension.spec.ts, cypress/integration/eventBus.spec.ts, cypress/integration/rowSpan.spec.ts, cypress/integration/sort.spec.ts, cypress/integration/summary.spec.ts, cypress/integration/validation.spec.ts, index.d.ts, src/dispatch/column.ts, src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/keyboard.ts, src/dispatch/sort.ts, src/event/gridEvent.ts, src/grid.tsx, src/helper/rowSpan.ts, src/helper/sort.ts, src/query/data.ts, src/query/keyboard.ts, src/store/data.ts, src/store/focus.ts, src/store/types.ts, src/store/viewport.ts, src/view/editingLayerInner.tsx, src/view/rowSpanCell.tsx, src/view/sortingButton.tsx, src/view/sortingOrder.tsx
**sort**
* changed `sortOptions` to `sortState`
* added the test cases
* unsort the data on calling `resetData`, `setColumns`, `clearData` API
* reduced the condition expression in `dispatch/sort.ts`
**dimension**
* added the test cases
* change the body height properly on calling `setHeight`, `setBodyHeight`, `setHeader` API
**rowSpan**
* added the test cases
* render the rowSpan cell properly on calling `resetData`, `setColumns` API
**validation**
* added the test cases
* validate the cell value on calling `resetData`, `setColumns` API
**summary**
* added the test cases
* `setSummaryColumnContent` is priority than defaultContent
**eventBus**
* added the test cases
* `onGridBeforeDestroy`
**setColumns API**
* created new uniqueKey and unsorted the data on calling setColumns
* considered …
=> fix: add test case and fix the related bug

cypress/integration/data.spec.ts, cypress/integration/editor.spec.ts, cypress/integration/lazyObservable.spec.ts, cypress/integration/sort.spec.ts, src/dispatch/column.ts, src/dispatch/data.ts, src/dispatch/focus.ts, src/dispatch/keyboard.ts, src/dispatch/mouse.ts, src/dispatch/sort.ts, src/helper/column.ts, src/helper/sort.ts, src/query/data.ts
* checked hidden property on calling sort API.
* checked hidden property on calling startEditing, finishEditing API.
* added that check/uncheck API test case.
---
=> fix: check the hidden property when edit, sort

src/dispatch/data.ts, src/dispatch/mouse.ts, src/dispatch/renderState.ts, src/query/mouse.ts, src/store/renderState.ts, src/store/types.ts, src/view/bodyArea.tsx, src/view/container.tsx, src/view/selectionLayer.tsx
* Fix to apply row hover style above selection layer
---
=> fix: row hover style above selection layer

cypress/integration/validation.spec.ts, src/helper/common.ts, src/helper/sort.ts, src/store/data.ts
* validation for editor input string value
---
=> fix: validation for editor input string value

src/dispatch/data.ts, src/dispatch/mouse.ts, src/query/clipboard.ts, src/query/data.ts, src/query/keyboard.ts, src/store/create.ts, src/store/focus.ts, src/store/selection.ts, src/store/types.ts
* endRowIndex follows the heights length
---
=> fix: client pagination rowheader selection

src/css/grid.css, src/dispatch/filter.ts, src/helper/dom.ts, src/view/filterLayerInner.tsx
* filter layer inner icon change
* apply button margin
* render second layer condition
* not init select box when unfilter
---
=> refactor: filter ui

cypress/.eslintrc.js, cypress/integration/columnOptions.spec.ts, cypress/integration/data.spec.ts, cypress/integration/dataSource.spec.ts, cypress/integration/editor.spec.ts, cypress/integration/eventBus.spec.ts, cypress/integration/filter.spec.ts, cypress/integration/rowHeaders.spec.ts, cypress/integration/validation.spec.ts, cypress/support/index.d.ts, cypress/support/index.js, src/dispatch/data.ts
* fixed that the value is not inserted for each column when appends the empty row(#634)
---
=> fix: insert empty value for each column as append the empty row(#634)

cypress/integration/data.spec.ts, src/dispatch/data.ts, src/dispatch/mouse.ts
* fixed that JS error has been caused as clicked the area of grid after removing the row(#708).
---
=> fix: JS error has been caused as clicked the area of grid after removing the row(#708).

src/helper/keyboard.ts, src/types.d.ts
* changed `keyNameMap` type to `const` type
---
=> fix: remove unnecessary keyboard type

src/view/bodyArea.tsx
* fixed that prevent to emit `mousedown` event on clicking scroll or empty area in grid body.
---
=> fix: prevent to emit mousedown event on clicking body area

cypress/integration/rowHeaders.spec.ts, src/dispatch/data.ts, src/store/data.ts, src/view/headerCheckbox.tsx, src/view/pagination.tsx
* fixed change initial checkedAllRows value.
* set initial checkbox state on mounting `headerCheckbox` component
---
=> fix: change initial checkedAllRows value

src/dispatch/mouse.ts
* changed target column name in mouseDownHeader function.
---
=> fix: change target column name in mouseDownHeader

src/dataSource/serverSideDataProvider.ts
* fixed `dataSource` callback function to set pagination option in case of getting valid pagination state
---
=> fix: modify datasource callback function

cypress/integration/filter.spec.ts, src/dispatch/filter.ts
* filter, unfilter API not call when column hidden
---
=> fix: filter, unfilter API not call when column hidden

cypress/integration/theme.spec.ts, src/view/container.tsx
* fix bug that not delete class when mouseout
---
=> fix: bug that not delete class when mouseout

cypress/integration/data.spec.ts, cypress/integration/filter.spec.ts, cypress/integration/sort.spec.ts, src/dispatch/data.ts, src/dispatch/filter.ts, src/dispatch/sort.ts
* update row number when changing data order(#730)
---
=> feat: update row number when changing data order(#730)

.github/auto-comment.yml, .github/stale.yml
* added `auto-comment`, `stale` probot config files.
---
=> chore: add probot config

cypress/integration/summary.spec.ts, package-lock.json, package.json, samples/basic.ts, src/dispatch/data.ts, src/dispatch/filter.ts, src/dispatch/sort.ts, src/dispatch/summary.ts, src/dispatch/types.ts, src/store/summary.ts
* apply summary after filtering, move page, sort
---
=> fix: filter summary

cypress/integration/filter.spec.ts, src/grid.tsx
* filter api with operator
---
=> fix: filter api with operator(#757)

packages/toast-ui.grid/cypress/integration/column.spec.ts, packages/toast-ui.grid/cypress/support/commands.js, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/mouse.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/column.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/query/selection.ts, packages/toast-ui.grid/src/renderer/types.d.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/create.ts, packages/toast-ui.grid/src/store/types.ts, packages/toast-ui.grid/src/types.d.ts, packages/toast-ui.grid/src/view/columnHeader.tsx, packages/toast-ui.grid/src/view/complexHeader.tsx, packages/toast-ui.grid/src/view/headerArea.tsx, packages/toast-ui.grid/src/view/headerColumn.tsx
* added customizing header column option(#759)
---
=> feat: customizing header column

packages/toast-ui.grid/src/css/grid.css, packages/toast-ui.grid/src/store/create.ts, packages/toast-ui.grid/src/store/dimension.ts, packages/toast-ui.grid/src/store/focus.ts, packages/toast-ui.grid/src/store/selection.ts, packages/toast-ui.grid/src/view/bodyArea.tsx, packages/toast-ui.grid/src/view/editingLayerInner.tsx
* fixed calculating wrong selection area and focus area caused unnecessary `scroll`
---
=> fix: wrong selection area

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/src/dispatch/keyboard.ts
* fixed that `editingStart` event has not been emitted by editing keyMap operation(#766)
---
=> fix: keymap editing

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/cypress/support/commands.js, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/src/dispatch/mouse.ts
* finished editing when mousedown header(rowHeader, columnHeader) area
---
=> fix: finish editing when mousedown header area

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/dispatch/mouse.ts, packages/toast-ui.grid/src/grid.tsx
* fixed `finishEditing` API
* legacy(**not recommended**)
* finishEditing(rowKey, columnName): save the `current editing value` and finish editing.
* finishEditing(rowKey, columnName, value): save the `value` as editing result and finish editing.
* current(**recommended**)
* finishEditing(): save the `current editing value` and finish editing.
* added `cancelEditing` API
* cancel editing(not save editing value)
* code
```js
grid.cancelEditing();
```
---
=> fix: finish editing api

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/support/commands.js, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/types.d.ts
* added `setRow` API.
* fixed cypress `getCellByIdx` command.
* fixed bug that sorting state is not maintained on calling appendRow API.
---
=> feat: add setRow API

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/data.ts
=> feat: move row api

packages/toast-ui.grid/src/view/bodyCell.tsx, packages/toast-ui.grid/src/view/bodyRow.tsx, packages/toast-ui.grid/src/view/rowSpanCell.tsx
* use prop rowIndex for performance
---
=> refactor: use prop rowIndex

packages/toast-ui.grid/examples/example11-row-headers.html
=> fix: row header example

packages/toast-ui.grid/cypress/integration/summary.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/summary.ts, packages/toast-ui.grid/src/dispatch/types.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/summary.ts, packages/toast-ui.grid/src/store/summary.ts, packages/toast-ui.grid/src/store/types.ts, packages/toast-ui.grid/src/types.d.ts, packages/toast-ui.grid/src/view/summaryBodyCell.tsx
* added summary values with filtering
* summaryValueMap
```js
{ 
sum, min, max, avg, cnt
filtered: {
sum, min, max, avg, cnt
}
}
```
---
=> fix: calculating summary with filtering

packages/toast-ui.grid/cypress/integration/column.spec.ts, packages/toast-ui.grid/cypress/integration/sort.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/dispatch/sort.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/column.ts, packages/toast-ui.grid/src/query/selection.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/types.ts, packages/toast-ui.grid/src/types.d.ts, packages/toast-ui.grid/src/view/complexHeader.tsx, packages/toast-ui.grid/stories/complexColumns.stories.ts
=> feat: header complex column(#742)

packages/toast-ui.grid/cypress/integration/selection.spec.ts, packages/toast-ui.grid/src/grid.tsx
* `getSelectionRange()`
* return type: `{ start: [number, number], end: [number, number] }`
```
{
start: [rowIndex, columnIndex],
end: [rowIndex, columnIndex]
}
```
---
=> feat: getSelectionRange API

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/dispatch/sort.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/array.ts, packages/toast-ui.grid/src/helper/observable.ts
* added array patch function to notify automatically
---
=> refactor: add array patch function

packages/toast-ui.grid/cypress/integration/header.spec.ts, packages/toast-ui.grid/src/renderer/types.d.ts, packages/toast-ui.grid/src/view/columnHeader.tsx
=> fix: add misssing render props in custom column header(#817)

package-lock.json, package.json, packages/toast-ui.grid/package-lock.json, packages/toast-ui.grid/package.json, packages/toast-ui.react-grid/package-lock.json, packages/toast-ui.react-grid/package.json, packages/toast-ui.react-grid/src/index.js, packages/toast-ui.vue-grid/package-lock.json
* prettier version up(1.16.0 -> 1.19.1)
---
=> chore: update prettier version(1.16.0 -> 1.19.1)

packages/toast-ui.grid/cypress/integration/filter.spec.ts, packages/toast-ui.grid/src/view/textFilter.tsx
=> fix: change event type (onKeyUp -> onInput)

packages/toast-ui.grid/src/theme/styleGenerator.ts
#688 
* apply validation theme with striped(custom) theme
---
=> fix: change validation css rule precedence

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/editor/text.ts, packages/toast-ui.grid/src/editor/types.d.ts, packages/toast-ui.grid/src/view/editingLayerInner.tsx
=> fix: change the type of returning value on text editor(#831)

packages/toast-ui.grid/cypress/integration/dom.spec.ts, packages/toast-ui.grid/cypress/integration/header.spec.ts, packages/toast-ui.grid/cypress/integration/state.spec.ts, packages/toast-ui.grid/src/view/complexHeader.tsx, packages/toast-ui.grid/src/view/headerArea.tsx
=> fix: modify wrong border height with complex header(#820)

packages/toast-ui.grid/src/css/grid.css, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/view/bodyCell.tsx, packages/toast-ui.grid/src/view/editingLayerInner.tsx, packages/toast-ui.grid/src/view/stateLayer.tsx
=> fix: call beforeDestroy hook for custom renderer in componentWillUnmount(#815)

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/src/view/editingLayerInner.tsx
* revert the converting editing value to number type to remove side effect of PR(#832)
---
=> fix: rollback PR(#832) to remove side effect

packages/toast-ui.grid/src/view/clipboard.tsx
* The copying the cell data or pasting the data to grid have not been operated in IE
* related issue(#835)
---
=> fix: modify wrong clipboard element target(#835)

packages/toast-ui.grid/cypress/integration/combinedFeatureTest.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/sort.ts
=> fix: data cannot be sorted with filter condition

packages/toast-ui.grid/.storybook/config.js, packages/toast-ui.grid/cypress/integration/column.spec.ts, packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/stories/dimension.stories.ts, packages/toast-ui.grid/stories/editor.stories.ts, packages/toast-ui.grid/stories/focus.stories.ts, packages/toast-ui.grid/stories/rowHeaders.stories.ts, packages/toast-ui.grid/stories/rowSpan.stories.ts, packages/toast-ui.grid/stories/sort.stories.ts, packages/toast-ui.grid/stories/state.stories.ts, packages/toast-ui.grid/stories/summary.stories.ts, packages/toast-ui.grid/stories/tree.stories.ts
* Refactoring content
* Data has been moved in each story for independence of each data.
* Removed duplicated integration test.
* Editor
* Added editing cell info on notes.
* Tree
* The story has been rewritten more detail as below.
* Tree Icon
* Expanded and Collapsed
* Row Header
* The story has been rewritten more detail as below.
* Row Num
* Checkbox Row Header
* Row Num And Checkbox Row Headers
* Custom Row Header
* Row Span
* The story has been rewritten more detail as below.
* Basic
* Row Span Focus
* Row Span Editor
* Row Span Selection
* Focus
* Added focused cell info on notes.
* Added Decorator to initialize the `theme`, `language` for consistency of test
---
=> refactor: storybook scenario

packages/toast-ui.grid/cypress/integration/relation.spec.ts, packages/toast-ui.grid/samples/relations.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/src/store/types.ts
=> fix: relation column relies on the order of column definition(#844)

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/src/dataSource/serverSideDataProvider.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/grid.tsx
=> fix: grid height is not updated after calling setPerPage api

packages/toast-ui.grid/cypress/integration/combinedFeatureTest.spec.ts, packages/toast-ui.grid/cypress/integration/filter.spec.ts, packages/toast-ui.grid/samples/relations.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/helper/common.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/src/store/helper/tree.ts, packages/toast-ui.grid/src/store/types.ts, packages/toast-ui.grid/src/view/selectFilter.tsx
* related issue(#816)
* if `formatter` returns the html entity, it will not applied to filter data and we only support `string` data on filtering with formatted value
```js
const columns = [
{
header: 'Col1',
name: 'col1',
formatter: function({ value }) {
return `<div>${value}<div>` // we don't support this case
}
}
];
```
* moved first page on unfiltering data
* PR needs to rebase master
---
=> fix: grid data cannot be filtered with formatted value

packages/toast-ui.grid/cypress/helper/customLayerRenderer.ts, packages/toast-ui.grid/cypress/integration/datePicker.spec.ts, packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/cypress/integration/renderer.spec.ts, packages/toast-ui.grid/src/store/column.ts
* Improved custom renderer config options for usability
```js
// before
const columns: OptColumn[] = [
{
name: 'score',
renderer: {
type: SliderRenderer,
}
}
];
// after
const columns: OptColumn[] = [
{
name: 'score',
renderer: SliderRenderer
}
];
```
---
=> feat: add custom renderer using type

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/rowHeaders.spec.ts, packages/toast-ui.grid/cypress/integration/selection.spec.ts, packages/toast-ui.grid/cypress/integration/sort.spec.ts, packages/toast-ui.grid/cypress/support/commands.js, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/cypress/support/index.js, packages/toast-ui.grid/samples/basic.ts, packages/toast-ui.grid/src/helper/sort.ts
=> fix: sort comparator(#864)

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/docs/en/custom-event.md, packages/toast-ui.grid/docs/ko/custom-event.md, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dataSource/helper/ajaxConfig.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/common.ts, packages/toast-ui.grid/src/types.d.ts, packages/toast-ui.grid/src/view/root.tsx
=> feat: `onGridUpdated` event(#866)

packages/toast-ui.grid/cypress/helper/runMockServer.ts, packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dataSource/getterRequest.ts, packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts, packages/toast-ui.grid/src/dataSource/mutationRequest.ts, packages/toast-ui.grid/src/dataSource/serverSideDataProvider.ts, packages/toast-ui.grid/src/dataSource/types.d.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/types/tui-pagination/index.d.ts
* related issue(#868)
* added missing type definition to `index.d.ts`
* removed `I` prefix in `index.d.ts`
---
=> feat: setRequestParams API(#868)

packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/cypress/integration/header.spec.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/query/column.ts, packages/toast-ui.grid/src/view/columnResizer.tsx
=> fix: the one of the child column of complex header cannot be hidden(#875)

packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts, packages/toast-ui.grid/src/dataSource/mutationRequest.ts, packages/toast-ui.grid/src/dataSource/types.d.ts, packages/toast-ui.grid/src/grid.tsx
=> feat: clearModifiedData API(#877)

packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/dispatch/viewport.ts
=> fix: scroll position cause the bug when calls resetData API(#890)

packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/types.ts, packages/toast-ui.grid/src/view/bodyArea.tsx, packages/toast-ui.grid/src/view/bodyCell.tsx, packages/toast-ui.grid/src/view/columnHeader.tsx, packages/toast-ui.grid/src/view/selectionLayer.tsx
* changed `undefined` style property to default value(empty string) in virtual dom.
---
=> fix: assign the default value(not `undefined`) to vdom style

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/helper/observable.ts
=> fix: add `enumerable` option to observable data

packages/toast-ui.grid/examples/data/basic-dummy.js, packages/toast-ui.grid/examples/data/tree-dummy.js, packages/toast-ui.grid/examples/example01-basic.html, packages/toast-ui.grid/examples/example02-complex-columns.html, packages/toast-ui.grid/examples/example03-custom-editor.html, packages/toast-ui.grid/examples/example04-custom-renderer.html, packages/toast-ui.grid/examples/example05-relation-columns.html, packages/toast-ui.grid/examples/example06-attributes.html, packages/toast-ui.grid/examples/example07-themes.html, packages/toast-ui.grid/examples/example08-date-picker.html, packages/toast-ui.grid/examples/example09-summary.html, packages/toast-ui.grid/examples/example10-data-source.html, packages/toast-ui.grid/examples/example11-row-headers.html, packages/toast-ui.grid/examples/example12-whitespace.html, packages/toast-ui.grid/examples/example13-i18n.html, packages/toast-ui.grid/examples/example14-tree.html, packages/toast-ui.grid/examples/example15-custom-event.html, packages/toast-ui.grid/examples/example16-frozen-columns.html, packages/toast-ui.grid/examples/example17-dummy-row.html, packages/toast-ui.grid/examples/example18-column-resize.html, packages/toast-ui.grid/examples/example19-sort.html, packages/toast-ui.grid/examples/example20-validation.html, packages/toast-ui.grid/examples/example21-header-align.html, packages/toast-ui.grid/examples/example22-setting-width-height.html, packages/toast-ui.grid/examples/example23-client-pagination.html, packages/toast-ui.grid/examples/example24-filter.html, packages/toast-ui.grid/examples/example25-large-data-performance.html, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/tuidoc.config.json
* modify example code to execute in IE
* What is the effective way to maintain example code?
* using [babel-standalone](https://babeljs.io/docs/en/babel-standalone) **vs** seperated code(real code to execute, displaying code in custom tag)
---
=> chore: modify example to execute in IE

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/index.d.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/event/gridEvent.ts
=> feat: add `onBeforeChange`, `onAfterChange` event params(#901)

packages/toast-ui.grid/cypress/integration/column.spec.ts, packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/helper/common.ts, packages/toast-ui.grid/src/helper/observable.ts, packages/toast-ui.grid/src/store/data.ts
* related issue: #763 
* related PR : #854 
---
=> feat: partial observable(#763)

packages/toast-ui.react-grid/.storybook/config.js, packages/toast-ui.react-grid/src/index.js, packages/toast-ui.react-grid/stories/index.stories.js
* related issue(#912)
* TODO: add `index.d.ts`😱
---
=> fix: react wrapper bind duplicated event handler(#912)

packages/toast-ui.grid/cypress/integration/clipboard.spec.ts, packages/toast-ui.grid/cypress/integration/header.spec.ts, packages/toast-ui.grid/cypress/integration/keyMap.spec.ts, packages/toast-ui.grid/docs/ko/validation.md, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/src/store/helper/tree.ts
* removed unnecessary TODO
* removed `defaultValues`
* moved test case(clipboard -> keyMap)
---
=> refactor: remove unnecessary TODO comment and `defaultValues`

packages/toast-ui.react-grid/README.md
There was a comma missing in the example
#936 rename
---
=> chore: update Readme.md (#936)

packages/toast-ui.grid/cypress/integration/datePicker.spec.ts, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/store/index.d.ts
=> fix: capitalization bug in type

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/rowHeaders.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/query/data.ts
* change header checkbox when `appendRow()`, `appendRows()`, `removeRows()`, `setRow()`
---
=> fix: change header checkbox status when append, remove row

packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts, packages/toast-ui.grid/src/dispatch/keyboard.ts
* related issue(#859, #949)
---
=> fix: add updated data to modifiedDataManager when removing content using `backspace`, `del` key 

packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/tree.ts
* related issue(#954)
* TODO: check monkey patch order problem
---
=> fix: moveRow api

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts
=> fix: checkbox `checked` status on calling `appendRows`, `setRow`, `appendRow`, `removeRow` API

packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/css/grid.css, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/query/tree.ts, packages/toast-ui.grid/src/store/helper/tree.ts
=> feat: tree expand resize

package-lock.json, package.json, packages/toast-ui.grid/package-lock.json, packages/toast-ui.grid/package.json
* applied release note to root project
---
=> chore: apply release note to root

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/tree.ts
* checkbox state is synced after manipulating data using API(`appendRow`, `removeRow`, `setRow`, `appendRows`)
* `checked` state of added data is not changed as default
* update `checked` and `rowNum` after manipulating tree data
---
=> fix: checkbox with row manipulation

packages/toast-ui.grid/package-lock.json, packages/toast-ui.grid/package.json
=> chore: move preact, @toast-ui/select-box, tslib to dev dependencies

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/cypress/integration/combinedFeatureTest.spec.ts, packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/cypress/support/commands.js, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/src/view/bodyArea.tsx
=> fix: prevent to occur scrollEnd event when scrolling horizontally

packages/toast-ui.grid/src/css/grid.css
=> fix: change global css to grid checkbox style(#984)

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/cypress/integration/focus.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/samples/tree.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/grid.tsx
* related issue(#986, #991)
---
=> fix: editing of the tree cell is disabled(#986, #991)

packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts
=> fix: js error occurred when calling setColumnValues API(#996)

packages/toast-ui.grid/cypress/integration/attributes.spec.ts, packages/toast-ui.grid/cypress/integration/focus.spec.ts, packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/cypress/integration/relation.spec.ts, packages/toast-ui.grid/cypress/support/commands.js, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/src/view/bodyRow.tsx
* added missing `tui-grid-cell-current-row` css on focused row
---
=> fix: add missing css(`tui-grid-cell-current-row`)

packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts
=> fix: the modified data should be cleared(#1005)

packages/toast-ui.react-grid/index.d.ts
=> fix: remove 'el' type in react-wrapper(#990)

packages/toast-ui.grid/docs/en/custom-editor.md, packages/toast-ui.grid/docs/en/custom-renderer.md, packages/toast-ui.grid/docs/en/date-picker.md, packages/toast-ui.grid/docs/ko/custom-column-header.md, packages/toast-ui.grid/docs/ko/custom-editor.md, packages/toast-ui.grid/docs/ko/custom-renderer.md, packages/toast-ui.grid/docs/ko/data-source.md, packages/toast-ui.grid/docs/ko/date-picker.md, packages/toast-ui.grid/docs/v4.0-migration-guide-kor.md, packages/toast-ui.grid/docs/v4.0-migration-guide.md, packages/toast-ui.grid/src/grid.tsx
* fixed wrong option description and broken link
* TODO: add datasource, custom-column-header en tutorial
---
=> docs: fix typo and broken link

packages/toast-ui.grid/docs/en/custom-column-header.md, packages/toast-ui.grid/docs/en/data-source.md, packages/toast-ui.grid/docs/en/infinite-scroll.md
* added english tutorial
* infinite scroll
* custom column header
* added option for dataSource after `v4.9.0`
---
=> docs: add tutorial

packages/toast-ui.grid/docs/en/themes.md, packages/toast-ui.grid/docs/ko/themes.md, packages/toast-ui.grid/examples/example07-themes.html, packages/toast-ui.grid/src/css/grid.css, packages/toast-ui.grid/src/view/bodyArea.tsx, packages/toast-ui.grid/src/view/rightSide.tsx, packages/toast-ui.grid/stories/theme.stories.ts
* The themes of vertical border and last cell border are not applied to grid.
* wrong calculated `tui-grid-scrollbar-frozen-border` width
---
=> fix: vertical border theme is not applied

packages/toast-ui.grid/src/view/bodyArea.tsx, packages/toast-ui.grid/src/view/summaryArea.tsx, packages/toast-ui.grid/stories/state.stories.ts
=> fix: the scroll bar is not displayed with empty data(#1035)

packages/toast-ui.grid/cypress/helper/runMockServer.ts, packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/cypress/integration/sort.spec.ts, packages/toast-ui.grid/docs/en/custom-event.md, packages/toast-ui.grid/docs/ko/custom-event.md, packages/toast-ui.grid/src/dataSource/getterRequest.ts, packages/toast-ui.grid/src/dataSource/serverSideDataProvider.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/sort.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/sort.ts, packages/toast-ui.grid/src/view/sortingButton.tsx, packages/toast-ui.grid/tuidoc.config.json, packages/toast-ui.grid/types/dataSource/index.d.ts, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/options.d.ts
* related issue(#1042)
* added event
* `beforeSort`
* `afterSort`
* `beforeUnsort`
* `afterUnsort`
* TODO
* refactoring: classify the sorting and unsorting for improving complicated event logic and state
---
=> feat: add `beforeSort`, `afterSort`, `beforeUnsort`, `afterUnsort` custom event

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/cypress/integration/filter.spec.ts, packages/toast-ui.grid/cypress/integration/sort.spec.ts, packages/toast-ui.grid/docs/en/custom-event.md, packages/toast-ui.grid/docs/ko/custom-event.md, packages/toast-ui.grid/src/dataSource/getterRequest.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/query/filter.ts, packages/toast-ui.grid/src/query/sort.ts, packages/toast-ui.grid/tuidoc.config.json, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/options.d.ts
* related issue(#1042)
* added event
* `beforeFilter`
* `beforeUnfilter `
* `afterFilter `
* `afterUnfilter `
---
=> feat: `beforeFilter`, `afterFilter`, `beforeUnfilter`, `afterUnfilter` custom event

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/types/store/column.d.ts
=> fix: cannot edit the tree cell when appending empty tree row(#1033)

packages/toast-ui.grid/types/store/data.d.ts
* related issue(#1014, #1031)
---
=> fix: add `object` type to `CellValue` type definition(#1014, #1031)

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/cypress/integration/sort.spec.ts, packages/toast-ui.grid/docs/en/custom-event.md, packages/toast-ui.grid/docs/ko/custom-event.md, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/filter.ts, packages/toast-ui.grid/src/dispatch/pagination.ts, packages/toast-ui.grid/src/dispatch/sort.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/common.ts, packages/toast-ui.grid/src/view/pagination.tsx, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/options.d.ts
* related issue(#1062)
* added event
* `beforePageMove`
* `afterPageMove`
---
=> feat: add `beforePageMove`, `afterPageMove` custom event

packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/lazyObservable.ts, packages/toast-ui.grid/src/dispatch/sort.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/helper/array.ts, packages/toast-ui.grid/src/helper/observable.ts, packages/toast-ui.grid/src/helper/sort.ts, packages/toast-ui.grid/src/store/data.ts
* related issue(#1028)
* prevent to stack the patched method recursively
* reduce the calling notify on making data observable
* `viewData` is newly created when sorting to improve the performance
* cache the `filteredIndex`
---
=> fix: improve the performance of sorting(#1028)

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/src/dispatch/pagination.ts, packages/toast-ui.grid/src/store/data.ts
=> fix: appended row is not displayed with infinite scrolling option

packages/toast-ui.grid/cypress/integration/dummyRows.spec.ts, packages/toast-ui.grid/src/view/bodyArea.tsx
=> fix: save the editing result when clicking the dummy cell

packages/toast-ui.grid/cypress/integration/relation.spec.ts, packages/toast-ui.grid/samples/relations.ts, packages/toast-ui.grid/src/store/column.ts
* removed column order dependency between relation columns
---
=> fix: remove order dependency between relation columns

packages/toast-ui.grid/cypress/integration/column.spec.ts, packages/toast-ui.grid/cypress/integration/combinedFeatureTest.spec.ts, packages/toast-ui.grid/cypress/integration/sort.spec.ts, packages/toast-ui.grid/src/dispatch/sort.ts, packages/toast-ui.grid/src/helper/sort.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/types/store/column.d.ts, packages/toast-ui.grid/types/store/data.d.ts
* related issue(#1095)
* TODO: add document
---
=> feat: add custom comparator option

packages/toast-ui.grid/cypress/integration/validation.spec.ts, packages/toast-ui.grid/src/dispatch/column.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/lazyObservable.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/observable.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/create.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/src/store/helper/tree.ts, packages/toast-ui.grid/src/store/helper/validation.ts, packages/toast-ui.grid/types/store/column.d.ts
* related issue(#1098)
* TODO: add document
---
=> feat: `unique` validation type

packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/src/view/container.tsx, packages/toast-ui.grid/src/view/pagination.tsx, packages/toast-ui.grid/stories/pagination.stories.ts, packages/toast-ui.grid/types/store/data.d.ts
* related issue(#1094)
* TODO: add document
---
=> feat: add `visiblePages` option

packages/toast-ui.grid/cypress/integration/validation.spec.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/validation.ts, packages/toast-ui.grid/src/store/helper/validation.ts, packages/toast-ui.grid/types/store/column.d.ts, packages/toast-ui.grid/types/store/data.d.ts
* add `errorInfo` to the result of `validate` API. The `errorInfo` has more detail information on validation result and it will replace the existing `errorCode` which is deprecated.
```js
// result of validate API. 
// errorInfo has errorCode and meta date for handling the validation result more conveniently.
[
{
rowKey: 1,
errors: [
{
columnName: 'c1',
// errorCode is deprecated.
errorCode: ['VALIDATOR_FN'],
errorInfo: [{ errorCode: "VALIDATOR_FN", customCode: 'CUSTOM_CODE' }]
}
]
},
{
rowKey: 2,
errors: [
{
columnName: 'c1',
errorCode: ['MIN'],
errorInfo: [{ errorCode: "MIN", min: 1000 }]
}
]
}
]  
```
* TODO: add document
---
=> feat: add meta information to the result of validate API

packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts, packages/toast-ui.grid/package-lock.json, packages/toast-ui.grid/package.json, packages/toast-ui.grid/src/editor/datePicker.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/columnCoords.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/src/store/dimension.ts, packages/toast-ui.grid/src/store/focus.ts, packages/toast-ui.grid/src/store/rowCoords.ts, packages/toast-ui.grid/src/store/selection.ts, packages/toast-ui.grid/src/store/summary.ts, packages/toast-ui.grid/src/store/viewport.ts, packages/toast-ui.grid/src/view/datePickerFilter.tsx
* update typescript version to `3.9.5`
---
=> chore: update typescript version to 3.9.5

.github/workflows/example-page-test.yml, packages/toast-ui.grid/package.json, packages/toast-ui.grid/scripts/createConfigVariable.ts, packages/toast-ui.grid/scripts/tsBannerGenerator.ts, packages/toast-ui.grid/tuidoc.config.json
* add example page test github action
---
=> chore: add example page test github action

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/docs/en/custom-event.md, packages/toast-ui.grid/docs/ko/custom-event.md, packages/toast-ui.grid/examples/example03-custom-editor.html, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/keyboard.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/query/keyboard.ts, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/options.d.ts
* add `beforeChange`, `afterChange` event. The event will be triggered on editing or pasting or deleting the data by keyMap
```js
grid.on('beforeChange', ev => {
/**
* {
*   origin: 'cell' | 'paste' | 'delete'
*   changes: [{ rowKey: 0, columnName: 'name', value: 'value', nextValue: 'nextValue', prevValue: 'prevValue' }]
* }
*/
console.log(ev);
});
```
---
=> feat: add `beforeChange`, `afterChange` event

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/src/grid.tsx
* fixed `getValue`API to return falsy value properly
---
=> fix: getValue API to return falsy value properly

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/src/query/rowSpan.ts
=> fix: script error when removing the rows on scrolling the bottommost data

packages/toast-ui.grid/src/dispatch/keyboard.ts
=> fix: cannot calculate the summary area when pasting the data

packages/toast-ui.grid/cypress/helper/assert.ts, packages/toast-ui.grid/cypress/helper/util.ts, packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/cypress/integration/combinedFeatureTest.spec.ts, packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/cypress/integration/datePicker.spec.ts, packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/cypress/integration/filter.spec.ts, packages/toast-ui.grid/cypress/integration/keyMap.spec.ts, packages/toast-ui.grid/cypress/integration/lazyObservable.spec.ts, packages/toast-ui.grid/cypress/integration/modifiedDataManager.spec.ts, packages/toast-ui.grid/cypress/integration/rowHeaders.spec.ts, packages/toast-ui.grid/cypress/integration/selection.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/keyboard.ts, packages/toast-ui.grid/src/dispatch/mouse.ts, packages/toast-ui.grid/src/query/clipboard.ts, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/query/keyboard.ts, packages/toast-ui.grid/src/store/focus.ts, packages/toast-ui.grid/src/view/bodyCell.tsx
* related issue(#1192, #1213)
---
=> fix: cannot editing the cell with client pagination

packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dataSource/manager/modifiedDataManager.ts, packages/toast-ui.grid/src/dispatch/lazyObservable.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/src/store/helper/validation.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/store/data.d.ts
=> fix: the structure of tree data is nested after `resetOriginData` API

packages/toast-ui.grid/docs/ko/setting-width-height.md
* added width option tutorial(`auto resizing`)
---
=> docs: add width option tutorial(`auto resizing`)

packages/toast-ui.grid/cypress/helper/assert.ts, packages/toast-ui.grid/cypress/integration/clientPagination.spec.ts, packages/toast-ui.grid/src/view/pagination.tsx, packages/toast-ui.grid/types/store/data.d.ts
* add tui pagination options(centerAlign, firstItemClassName, lastItemClassName, template)
---
=> fix: add centerAlign page options

package-lock.json, packages/toast-ui.grid/cypress/integration/renderer.spec.ts, packages/toast-ui.grid/docs/en/custom-renderer.md, packages/toast-ui.grid/docs/ko/custom-renderer.md, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/renderer/default.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/types/options.d.ts, packages/toast-ui.grid/types/store/column.d.ts
* added default renderer option
* users can define the renderer options for default renderer
```js
const columns = [
{
name: 'name',
renderer: {
styles: {
fontWeight: '500',
},
attributes: {
myCustom: 'my-custom',
title: (props: CellRendererProps) => `my ${props.value}`,
},
classNames: ['my-class'],
},
},
];
const grid = new Grid({
columns, 
// ...
})
```
---
=> feat: add option for default renderer

.github/workflows/example-page-test.yml, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/tree.ts
=> fix: display the hidden child nodes after editing the tree

packages/toast-ui.grid/cypress/helper/runMockServer.ts, packages/toast-ui.grid/cypress/integration/dataSource.spec.ts, packages/toast-ui.grid/src/grid.tsx
When I use setPerPage function, I also usually used like readData function to get data from server.
I modified setPerPage with adding data parameter in the grid.ts
---
=> feat: modify setPerPage function with Data

packages/toast-ui.grid/src/css/grid.css
**selectbox**
as-is
**to-be**
**checkbox**
as-is
to-be
---
=> fix: selectbox, checkbox editor height

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/src/editor/select.ts
=> fix: emit script errors when data is not in the select box list

packages/toast-ui.grid/src/view/filterLayerInner.tsx
* related issue(#1295)
as-is
to-be
---
=> fix: wrong filter layer position

packages/toast-ui.grid/cypress/helper/util.ts, packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/docs/en/custom-event.md, packages/toast-ui.grid/docs/ko/custom-event.md, packages/toast-ui.grid/src/css/grid.css, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/column.ts, packages/toast-ui.grid/src/helper/dom.ts, packages/toast-ui.grid/src/query/draggable.ts, packages/toast-ui.grid/src/query/tree.ts, packages/toast-ui.grid/src/renderer/rowHeaderDraggable.ts, packages/toast-ui.grid/src/store/column.ts, packages/toast-ui.grid/src/store/create.ts, packages/toast-ui.grid/src/store/helper/tree.ts, packages/toast-ui.grid/src/view/bodyArea.tsx, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/options.d.ts, packages/toast-ui.grid/types/renderer/index.d.ts, packages/toast-ui.grid/types/store/column.d.ts, packages/toast-ui.grid/types/store/data.d.ts
* added `draggableRow` option and D&D feature
```js
const grid = new tui.Grid({
el: document.getElementById('grid'),
data: gridData,
// added option
draggableRow: true,
// ...
});
```
---
=> feat: drag and drop to move row

packages/toast-ui.grid/docs/en/data-source.md
added missing `pagination` property in DataSource response
=> docs: add missing pagination property in DataSource response

packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/tree.ts
=> fix: drop wrong position in tree

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/view/bodyArea.tsx
* added `appended` property to `drag` event
---
=> fix: add `appended` property to `drag` event

packages/toast-ui.grid/src/view/selectFilter.tsx
=> fix: emit script error in IE when checking filter value

packages/toast-ui.grid/src/view/clipboard.tsx
=> fix: cannot paste the data in chrome

packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/view/bodyArea.tsx
* fixed `targetRowKey` prop when moving to the bottommost with tree data. `targetRowKey` prop should be `null`
---
=> fix: drop event property

packages/toast-ui.grid/cypress/integration/dimension.spec.ts, packages/toast-ui.grid/src/dispatch/renderState.ts, packages/toast-ui.grid/src/view/bodyCell.tsx, packages/toast-ui.grid/src/view/bodyRow.tsx
=> fix: the row height is adjusted incorrectly when the column are added dynamically

packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/dispatch/keyboard.ts, packages/toast-ui.grid/src/query/data.ts
=> fix: paste the data with filtered data

packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/tree.ts
* fixed that modification code is registered with `CREATE`, `DELETE` when moving the tree row. The modification code should be `UPDATE` when moving the tree row.
---
=> fix: modification code is registered with `CREATE`, `DELETE` when moving the tree row

packages/toast-ui.grid/cypress/integration/contextMenu.spec.ts, packages/toast-ui.grid/docs/ko/contextMenu.md, packages/toast-ui.grid/src/css/grid.css, packages/toast-ui.grid/src/dispatch/clipboard.ts, packages/toast-ui.grid/src/dispatch/contextMenu.ts, packages/toast-ui.grid/src/dispatch/create.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/constant.ts, packages/toast-ui.grid/src/helper/dom.ts, packages/toast-ui.grid/src/i18n/index.ts, packages/toast-ui.grid/src/query/clipboard.ts, packages/toast-ui.grid/src/store/contextMenu.ts, packages/toast-ui.grid/src/store/create.ts, packages/toast-ui.grid/src/view/bodyArea.tsx, packages/toast-ui.grid/src/view/container.tsx, packages/toast-ui.grid/src/view/contextMenu.tsx, packages/toast-ui.grid/src/view/contextMenuItem.tsx, packages/toast-ui.grid/src/view/headerArea.tsx, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/options.d.ts, packages/toast-ui.grid/types/store/contextMenu.d.ts, packages/toast-ui.grid/types/store/index.d.ts
**Add context menu feature**
```js
const grid =tui.Grid({
// ...
contextMenu:  [
[
{
name: 'id1',
label: 'menu1',
action: 'copyRows',
classNames: ['my']
},
{
name: 'id2',
label: 'menu2',
action: () => {
console.log('menu2');
},
subMenu: [
{
name: 'id3',
label: 'subMenu1',
},
],
},
],
[
{
name: 'id4',
label: 'menu3',
action: () => {
console.log('menu3');
}
},
],
],
// ...
});
```
**default context menu**
---
=> feat: context menu

packages/toast-ui.grid/docs/en/data-source.md
fix wrong word `content -> contents`
---
=> Docs: content -> contents fix wrong word

packages/toast-ui.grid/docs/ko/data-source.md
Fix wrong word
createData method is POST, but docs write GET
---
=> Docs: fix wrong word in data-source.md

packages/toast-ui.grid/cypress/integration/eventBus.spec.ts, packages/toast-ui.grid/src/dispatch/focus.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/view/clipboard.tsx, packages/toast-ui.grid/src/view/editingLayer.tsx, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/options.d.ts
* added `keydown` event
* modified `editingfinish` event
* added editing info property to know that whether to save the value or be triggered by key
---
=> feat: `keydown` event

packages/toast-ui.grid/cypress/integration/tree.spec.ts, packages/toast-ui.grid/src/dispatch/tree.ts, packages/toast-ui.grid/src/view/bodyArea.tsx
* fixed infinite loop when appending tree row
**as-is**
**to-be**
**TODO**: Refactoring for Grid Row Data for maintaining.😡😡😡
---
=> fix: infinite loop when appending tree row

packages/toast-ui.grid/cypress/integration/keyMap.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts
* fixed that the user cannot select the cell after calling `appendRows()` API
* related issue(#1446)
---
=> fix: cannot select the cell after calling `appendRows()` API

packages/toast-ui.grid/src/view/filterLayerInner.tsx, packages/toast-ui.grid/stories/filter.stories.ts
Fix the issue that showing the filter layer in the wrong position when clicking the filter button of another column
Fix the issue that showing the filter layer in the wrong position when clicking the filter button of another column
**As-Is**
**To-Be**
---
=> fix: wrong position of filter layer when click other column

packages/toast-ui.grid/webpack.config.js
* fixed xlsx external namespace
* `XLSX` -> `xlsx`(commonjs, amd)
---
=> fix: change xlsx external namespace

.github/actions/build-cache/action.yml, .github/actions/install-dependencies/action.yml, .github/actions/publish-docs/action.yml, .github/actions/publish-package/action.yml, .github/actions/publish-to-cdn/action.yml, .github/workflows/publish-docs.yml, .github/workflows/publish-wrapper.yml, .github/workflows/publish.yml, package-lock.json, packages/toast-ui.grid/package-lock.json, packages/toast-ui.grid/package.json, packages/toast-ui.grid/scripts/publishToCDN.js, packages/toast-ui.grid/scripts/wrapperUpdate.js, packages/toast-ui.react-grid/package-lock.json, packages/toast-ui.vue-grid/package-lock.json
- Add workflow for publishing automation.
- One-click to publish documents and to NPM (also wrappers), CDN.
---
=> chore: add publish automation

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/integration/export.spec.ts, packages/toast-ui.grid/docs/ko/export.md, packages/toast-ui.grid/src/dispatch/export.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/export.ts, packages/toast-ui.grid/types/store/export.d.ts
- Fix to use the formatted value as a default when using the export function.
- Make it selectable using the `useFormattedValue` option (default: `true`).
---
=> fix: export with formatted values

packages/toast-ui.grid/docs/en/setting-width-height.md, packages/toast-ui.grid/docs/ko/setting-width-height.md, packages/toast-ui.grid/src/grid.tsx
- Related issue: #1449 
- Fix where the default values of options were written incorrectly.
---
=> docs: fix incorrect description of docs (fix #1449)

packages/toast-ui.grid/examples/example24-filter.html
- Related issue: #1452 
- Fix incorrect example on how to pass options to filter.
---
=> docs: fix incorrect example of filter options (fix #1452)

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/dispatch/export.ts
- Related issue: #1495 
- Fix to export in UTF-8 format so that Unicode is not broken when exporting to csv.
<br>
- \+ Remove unnecessary comment and correct typo
---
=> fix: export csv to UTF-8 format (fix #1495)

packages/toast-ui.grid/src/helper/googleAnalytics.ts
- Related issue: #1450 
- Fix a script error that occurred when third-party cookies were blocked in incognito mode.
- If browser is set to block third-party cookies, do nothing.
---
=> fix: error occurs on usageStatistics in incognito mode (fix #1450)

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/cypress/support/index.d.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/constant.ts, packages/toast-ui.grid/src/store/data.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/store/data.d.ts
* Added API to enable/disable specific cell.
* Worked by using the basic logic of the row and column disable function.
* If that the cell is in a row number or draggable column, do nothing.
**Disable cell**
**enable cell**
---
=> feat: enable/disable specific cell

packages/toast-ui.grid/cypress/integration/editor.spec.ts, packages/toast-ui.grid/cypress/integration/validation.spec.ts, packages/toast-ui.grid/src/helper/observable.ts, packages/toast-ui.grid/src/store/data.ts
* Fixed so that revalidation is not performed when modifying class name.
---
=> fix: check validation when only data modified

packages/toast-ui.react-grid/package.json, packages/toast-ui.vue-grid/package.json
Replaced deprecated links on package.json with newer links.
---
=> chore: replace invalid links on package.json

.github/stale.yml, LICENSE, README.md, packages/toast-ui.grid/package.json, packages/toast-ui.grid/tuidoc.config.json, packages/toast-ui.react-grid/package.json, packages/toast-ui.vue-grid/package.json
- Renamed organization(corporation) name to 'NHN Cloud'
---
=> docs: rename corp name to `NHN Cloud`

packages/toast-ui.grid/cypress/integration/data.spec.ts, packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/query/data.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/store/data.d.ts
* Added `removeRows` API to delete multiple rows at once.
* If passed an array of `rowKeys`, delete all rows corresponding to each `rowKey`.
* If there is no row corresponding to the given `rowKeys`, no action is taken.
---
=> feat: add remove rows API

packages/toast-ui.grid/src/i18n/index.ts
Adds Dutch translation to the labels
=> (i18n) Add Dutch translation

packages/toast-ui.grid/src/dispatch/data.ts, packages/toast-ui.grid/types/options.d.ts
* Fixed an issue that the `setRows` API was not working correctly.
* The logic that finds continuous row data doesn't work correctly.
* It was not working correctly and too complex, I fixed it correctly and easily.
---
=> fix: setRows api not works correctly

packages/toast-ui.grid/src/dispatch/data.ts
* Fixed an issue where `removeRows` API was too slow.
* It was slow because every time deleted a row, it iterates to update `sortKey` of all the data.
* So I fixed it to update `sortKey' after deleting all data.
---
=> fix: too slow removeRows API

packages/toast-ui.grid/cypress/integration/export.spec.ts, packages/toast-ui.grid/docs/ko/export.md, packages/toast-ui.grid/src/dispatch/contextMenu.ts, packages/toast-ui.grid/src/dispatch/export.ts, packages/toast-ui.grid/src/grid.tsx, packages/toast-ui.grid/src/helper/browser.ts, packages/toast-ui.grid/src/i18n/index.ts, packages/toast-ui.grid/src/query/export.ts, packages/toast-ui.grid/src/store/contextMenu.ts, packages/toast-ui.grid/types/event/index.d.ts, packages/toast-ui.grid/types/index.d.ts, packages/toast-ui.grid/types/options.d.ts, packages/toast-ui.grid/types/store/contextMenu.d.ts
* Added the ability to export to `.txt` format when exporting.
* For this purpose, Export to Text has been added to the default context menu.
* And added the `beforeExport` and `AfterExport` events to pass complext header data as arguments.
---
=> feat: export to txt format
